### ISSUE TITLE
How to combine with Reshade?

### ISSUE THREAD

**Issue by v00d00m4n** [Kaldaien/FAR#1]
I tried it old UnX way

[Import.ReShade64]
Architecture=Win64
Filename=ReShade64.dll
Role=ThirdParty
When=Early

and

[Import.dxgi]
Architecture=Win64
Filename=ReShade\dxgi.dll
Role=ThirdParty
When=Early

None works.  Judging by lack of log file from reshade, special k does not even load it.

Can you please document how special K import works with all possible values and features?
And i really hope filename supports relative path, because reshade and some other dlls like this works when they have same as special k use, so the only way to keep 2 dlls with same name is to move one into subfolder.

**Comment by jvatt** [comment]
This works:

[Import.ReShade]
Architecture=x64
Filename=ReShade64.dll
Role=ThirdParty
When=Early

**Comment by Drakonas** [comment]
With 0.1.0 the game seems to crash upon gameload with the above comment's code copied into the dxgi.ini. (I properly named the ReShade DLL and INI)

**Comment by drdaxxy** [comment]
Use When=PlugIn instead of When=Early. Note that "PlugIn" is case sensitive, i.e. "Plugin" won't work.

**Comment by Zanderat** [comment]
> 
> 
> This works:
> 
> [Import.ReShade]
> Architecture=x64
> Filename=ReShade64.dll
> Role=ThirdParty
> When=Early
> 
> I think you also need to rename reshades dxgi.ini to ReShade64.ini
> 
> Edit: It seems to sometimes break the SpecialK overlay (ctrl+shift+O). Might be a timing issue? What other values can we add for the 'When' parameter?

When=Early worked for me.
