### ISSUE TITLE
native 4K on 4K fullscreen mode

### ISSUE THREAD

**Issue by jerome-birembaut** [Kaldaien/FAR#10]
hello
do you know if we can force native 4K when we choose 4K fullscreen mode?
the native resolution seem to be 2K...

**Comment by Kaldaien** [comment]
As long as you are not using third-party software, native resolution should be the same in fullscreen mode. That's what the software is designed to fix.

**Comment by jerome-birembaut** [comment]
i set the game at 4k fullscreen resolution,
the frame buffer res is 3840x2160, 4K
and the window res is 2560x1680 2K ( i think )

so i don't undestand, the windows size should be   3840x2160 too?
![res](https://cloud.githubusercontent.com/assets/625091/24335724/3f502162-1283-11e7-8afb-2a2bf91f3b9c.jpg)

**Comment by jerome-birembaut** [comment]
i find the solution,
[Render.DXGI]
Scaling was set to "DontCare"
i changed it to Scaling=Unspecified 
and not it's in 4K
also set
[NVIDIA.API]
Disable to true

the game is so nice now and thanks to fullscreen my 1080SLI work just as expected, solid 60fps!

nice work indeed!
