### ISSUE TITLE
`Use Gamepad Freelook` snaps back to the player

### ISSUE THREAD

**Issue by Fusion86** [Kaldaien/FAR#103]
When you enable `Use Gamepad Freelook` the camera snaps back to the player whenever you stop pushing  the joysticks. Is this the intended behavior?

I am asking this because I added a toggle in the menu that enables the built-in free camera, which is very similar to the `Use Gamepad Freelook` feature except that the camera does NOT snap back to the player when you stop pushing the triggers (it only snaps back when you disable the freecam).

**Comment by Fusion86** [comment]
Furthermore, the address which is written to enable the in-game freecam (not gamepad freelook) is also referenced in nier.cpp.

```cpp
float*  pRoll      = reinterpret_cast <float  *> (0x141415B90);//1415EB990;
```

This variable however is never used. Maybe the addresses changed and this is just pure coincidence, or maybe Kaldaien ment to add a toggle for the in-game freecam but never did (however the variable name wouldn't make sense in that case).

**Comment by Idearum** [comment]
I don't think that functionality ever went out from the beta stage. It is based IDK31 and Smithfield's work on the freelook camera, and Kaldaien probably had intentions to work a bit more on it, but other stuff came inbetween as they tend to do.

I'll link Kaldaien to this thread, though, so hopefully you'll get a reply. Posting here is almost guaranteed to go unnoticed, and the [Steam thread](http://steamcommunity.com/groups/SpecialK_Mods/discussions/3/1334600128973500691/) for the mod is much more likely to see replies.
