### ISSUE TITLE
Cannot get FPS uncap to work anymore

### ISSUE THREAD

**Issue by Aoshi5180** [Kaldaien/FAR#104]
I think a windows update somehow messed with my game. I recently updated FAR (which used to work 100% fine a few weeks ago) but today I cannot get the FPSuncap to work anymore. I have uninstall and reinstalled FAR to no success. 

Hitting CTRL shift + just crashes the game.

**Comment by Idearum** [comment]
Please provide your logs from the logs subfolder of the game. These files are the most interesting: dinput8.log, dxgi.log (might not exist), crash.log, and modules.log. Upload these to http://pastebin.com and link them here.

**Comment by Aoshi5180** [comment]
**dxgi.log** https://pastebin.com/Utq2WZhG 
**dinput8.log** https://pastebin.com/FbLuWwg6
**modules.log** https://pastebin.com/Dizycfz3

Hope that works. I've tried running the game/and/or steam as admin and haven't had much success.

**Comment by Idearum** [comment]
You have two older versions of FAR installed and running simultaneously. Remove dxgi.dll which contains the older version. That might fix your issue.

Your dinput8.dll version also contains an out of date version of FAR, which might or might not be the cause as well. If you check the file version of the DLL file (right click -> properties -> Details) it says 0.8.30.3. The latest version of FAR (v0.7.0.14) should say 0.8.47.4 in that section.

I am not certain what version of FAR you actually have installed in dinput8.dll, but it's somewhere between FAR v0.7.0.0 (which says 0.8.25.0 in that section) and the latest v0.7.0.14 (which says 0.8.47.4), so you're at least running FAR 0.7.0.x.

Generally speaking all FAR 0.7.0.x versions usually work, and I believe the latest version might have an issue or two that needs to be fixed, so you might not have to update it further if the FPS unlocker works as expected after you remove dxgi.dll. But if it doesn't, reinstall FAR using the latest version that's contained within the FAR_0_7_0_14.7z archive on the release tab.

**Comment by Idearum** [comment]
Also, please be aware that the FPS unlocker generally isn't recommended for regular gameplay as it usually causes scripted events to break here and there. Use it at your own risk, basically.

**Comment by Aoshi5180** [comment]
That worked! Deleting those files (which I guess didn't uninstall when I uninstalled it in the first place) and reinstalling worked. Everything seems fine now. Thank you so much you big genius.
