### ISSUE TITLE
NieR runs in background

### ISSUE THREAD

**Issue by teirce** [Kaldaien/FAR#105]
Newest version of FAR causes NieR to run in the background. 

When I attempt to install an old version, an update prompt comes up and does not allow the install to continue.

Either fix the patch or do not force updates on users.

**Comment by Idearum** [comment]
Remove all files and folders in the game folder until only these remain: https://steamuserimages-a.akamaihd.net/ugc/808804068655852551/1CC119D2F8F8A2C2AD9519FA15027333A263C31D/

Then reinstall FAR using the automated installer from scratch.


> or do not force updates on users.

Updating is optional. You are presented with the choice of ignoring the update for X number of hours/days or permanently.
