### ISSUE TITLE
Always Close.

### ISSUE THREAD

**Issue by aszksbdje** [Kaldaien/FAR#112]
After a few minutes of playing, the game suddenly closed
This is the crash log file that I get.

[crash.log](https://github.com/Kaldaien/FAR/files/1791611/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1791612/dinput8.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1791613/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1791614/steam_api.log)

**Comment by Idearum** [comment]
FAR does not support illegitimate versions. Buy the game.

> 03/07/2018 20:49:16.410: [ Module ]  ( 00007FFFE2510000h + 00901120 )   -:< SteamInternal_CreateInterface                                    >:-   D:\GAMES\Nier Automata\steam_api64.dll
 ----------------------  [File Ver]    Steam Client API (buildbot_winslave007@WUS)  01.0.1.08

**Comment by febrianbs** [comment]
Eh.... 
:sob: :sob: :sob: 

Thank You.... :sweat_smile: :sweat_smile: :sweat_smile:
