### ISSUE TITLE
game wont open

### ISSUE THREAD

**Issue by N1flheimr** [Kaldaien/FAR#113]
i downloaded FAR the first time i open the game it worked then i relaunch it and it wont open(when click play my steam become in game but it closed after awhile)if i delete dinput8.dll it worked again,and when i use the old one(without updating) when i press CTRL+SHIFT+backspace my keyboard didnt work until i press CTRL SHIFT backspace again

**Comment by Idearum** [comment]
Typically a sign that you have a third-party application running that's interfering with FAR. The usual suspects include: RTSS/Afterburner, Dxtory, FRAPS, MSI Nahimic, Razer's software, etc.

Can't say more without your modules.log and dinput8.log files from the log subfolder of the game.
