### ISSUE TITLE
After install FAR by SKIM64, I can't start game

### ISSUE THREAD

**Issue by kin-ko774** [Kaldaien/FAR#114]
it doesn't start. 

[crash.log](https://github.com/Kaldaien/FAR/files/1792945/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1792946/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/1792947/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/1792948/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1792949/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1792950/steam_api.log)

it's all crash log.

**Comment by Idearum** [comment]
Bandicam is hooking the game. It's either that, or you have something else that's causing it. The usual suspects are RTSS/Afterburner, Dxtory, FRAPS, MSI Nahimic, Razer's software, etc.
