### ISSUE TITLE
Controller D-pad and Left Joystick swapped?

### ISSUE THREAD

**Issue by JimmyFagguette** [Kaldaien/FAR#115]
I'm playing with a Logitech Controller, so it has the layout of an Playstation controller (though calls the buttons ABXY), I had the fullscreen border glitch so downloaded this plugin, but it has swapped my d-pad and joystick around, so the joystick toggles weapons and stuff and the d-pad controls movement. Obviously playing the game with a d-pad is horrendous, but I can't find anyway to reverse it though in game controller setup or with the FAR menu. Please help, I bought this game 2 days ago and just want to look at anime ass.
(I massively doubt it has anything to do with it, but with the d-pad and joystick switched my controller would be in the same layout as an Xbox controller, so maybe FAR is remapping it somehow?)

**Comment by Idearum** [comment]
Are you certain that you didn't mistakenly touch the physical switch/button on the controller that swaps these around? I helped a user once whom had a MODE button or something like that on the controller that automatically swapped these things.

If you want to and post your controller model I can see what I can google up on it.

**Comment by JimmyFagguette** [comment]
@Idearum Wow, yeah you're completely right. I only got this controller yesterday so didn't know what the button did, and wasn't aware of ever pressing it. Thanks for the help man.
