### ISSUE TITLE
FAR keeps draining Non-paged Pool leading to stutter

### ISSUE THREAD

**Issue by halibonga** [Kaldaien/FAR#117]
Hi, my game starts to stutter after a while of playing, and it gets worse and worse, I opened task manager and sees that Non-paged pool of the memory is at 4GB and still rising. It seems there's other people with the exact same issue as well (Post #2434 and #2437):

http://steamcommunity.com/groups/SpecialK_Mods/discussions/3/1334600128973500691/?ctp=82#c1471967615885770509

Please look into this! Much appreciated!

**Comment by Idearum** [comment]
Try and install an older version of the mod. I've heard 0.7.0.9 seems to work fine for some.
