### ISSUE TITLE
when enable OSD game will be crash

### ISSUE THREAD

**Issue by HSIA0116** [Kaldaien/FAR#118]
when i enable OSD(ctrl+shift+O)
it will crash
Im using far0.7.0.23

[CEGUI.log](https://github.com/Kaldaien/FAR/files/1803494/CEGUI.log)
[crash.log](https://github.com/Kaldaien/FAR/files/1803495/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1803496/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/1803497/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/1803498/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1803499/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1803501/steam_api.log)

**Comment by Idearum** [comment]
You seem to be running the global injector of Special K as well, which might or might not be causing it. Test by disabling injection for the global injector, and see if NieR:Automata performs better with the local injector you've installed in the game folder.

If it doesn't, try and remove dinput8.ini from the game folder to reset your configuration for the mod.

**Comment by lulalala** [comment]
When I try to enable OSD (via hot key, or via control panel GUI, the game would exit immediately. The crash.log is empty though.

I didn't use global injector, but just used SKIM to install FAR.

I removed dinput8.ini, but the same still happened.

My other logs are: https://gist.github.com/lulalala/ac3240cbe32365c449702816ea71266f
