### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by jackallee9527** [Kaldaien/FAR#119]
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/1805612/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/1805613/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1805614/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1805615/steam_api.log)
[crash.log](https://github.com/Kaldaien/FAR/files/1805616/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1805617/dinput8.log)

I bought NieR from steam,
After i install FAR from SKIM.exe , game crash every time,
here is my crash log ,can u help ?

**Comment by Idearum** [comment]
The logs looks clean, but I believe something might be interfering with the OSD component. Could you open dinput.ini and change "EnableCEGUI=true" to "EnableCEGUI=false" ? It should be near the top. Then see if that solves it.

**Comment by jackallee9527** [comment]
it's works  ...
I can normal open game now, thanks.

is there any way to find out what   interfering the OSD component ?

**Comment by Idearum** [comment]
What you could also do is download this archive: https://github.com/Kaldaien/FAR/releases/download/far_070/FAR.7z and extract **only** the CEGUI folder contained within to the game folder, and see if that solves it (you'll have to change EnableCEGUI back to true). Latest version of the mod have CEGUI embedded within itself, which might be responsible for the crash.

If that have no effect then it's almost certainly a third-party tool or application causing it, and you should probably start exiting/shutting down running stuff until you find what's causing it.
