### ISSUE TITLE
How do I disable the "HUD" on the top left that displays metrics?

### ISSUE THREAD

**Issue by Zignd** [Kaldaien/FAR#12]
![20170323221410_1](https://cloud.githubusercontent.com/assets/3194806/24276587/7cd18928-1016-11e7-8ac1-e41131adcf3b.jpg)

**Comment by Keith94** [comment]
See https://github.com/Kaldaien/SpecialK/issues/17

**Comment by Zignd** [comment]
Thanks @Keith94!
