### ISSUE TITLE
Random crashs and black screens

### ISSUE THREAD

**Issue by gutts12** [Kaldaien/FAR#120]
[steam_api.log](https://github.com/Kaldaien/FAR/files/1817767/steam_api.log)
[ReShade64.log](https://github.com/Kaldaien/FAR/files/1817788/ReShade64.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1817791/modules.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/1817792/game_output.log)
[crash.log](https://github.com/Kaldaien/FAR/files/1817793/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1817794/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/1817795/dxgi_budget.log)

Hi,can u help me ?my game crashs in random moments after 30~40 min of gameplay and sometimes ,the game leave a black screen when i still playing the game or when i press alt+tab for leave the game.

**Comment by Idearum** [comment]
Validate game files through Steam and disable the touch input service of Windows (it's injecting its DLL into the game):

> 03/15/2018 23:00:27.662: [ Module ]  ( 00007FFA64020000h + 00692224 )   -:< EndCaretTracking                                                 >:-   C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
03/15/2018 23:00:27.663: [File Ver]    Touch Keyboard and Handwriting Panel Text Services Framework  10.0.16299.15 (WinBuild.160101.0800)

If that doesn't solve it, then you most likely have some other third-party stuff that messes with the game.

> the game leave a black screen

That sounds like the white screen issue and can't fully be solved. This guide have a chapter on it with steps you can take to at least lower the chance of it happening: http://steamcommunity.com/sharedfiles/filedetails/?id=914437196 (chapter Issues -> The White Screen Issue)

**Comment by gutts12** [comment]
Hi,so,unfortunately this not work ,validate game files,using diferent versions of the mod,changing the affinity, nothing solve the issues,but thanks for all.
