### ISSUE TITLE
Crash when saving after credits

### ISSUE THREAD

**Issue by charagarlnad** [Kaldaien/FAR#122]
I crash only when trying to save after the credits right before Chapter 11:
[game_output.log](https://github.com/Kaldaien/FAR/files/1822139/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1822140/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1822141/steam_api.log)
[CEGUI.log](https://github.com/Kaldaien/FAR/files/1822142/CEGUI.log)
[crash.log](https://github.com/Kaldaien/FAR/files/1822143/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1822144/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/1822145/dxgi_budget.log)

**Comment by Idearum** [comment]
Validate game files through Steam. Corrupt game files are almost always the cause for repeatable game crashes.

**Comment by charagarlnad** [comment]
Validating reports that all the files are fine, so I don't think its that.
