### ISSUE TITLE
"Special K Software Install" failed (Edit: instant crash)

### ISSUE THREAD

**Issue by apflu** [Kaldaien/FAR#123]
After using Autoinstaller (SKIM64.exe) it shows up a window with a progress bar.
![capture](https://user-images.githubusercontent.com/25970844/37834942-4cf93d8c-2eaf-11e8-9561-ebf406f51078.PNG)
If I click on the "yes" button, the bar will instantly goes full and turns red.
![capture](https://user-images.githubusercontent.com/25970844/37834997-6926b282-2eaf-11e8-9fef-f27144453f0a.PNG)
If I just close it, the installer will clean up anything it downloaded and nothing will be changed.
My OS is Windows 7.

Any help are welcomed. Thank you for your time reading it.

**Comment by Idearum** [comment]
Install it manually. Or make an exception for SKIM64.exe within your anti-virus protection as that might be what's preventing it from working properly. Or just install it manually.

If you do install it manually, when the mod prompts you about updating on the first launch you can set it to Never as you already have the latest available version.

**Comment by apflu** [comment]
Thank you for your reply.
I've manually installed FAR under the guild http://steamcommunity.com/sharedfiles/filedetails/?id=914437196
After the manually installation i've deleted the config file under "Documents" (for both SpecialK under "My Mods" and game under "My Games") and restarted my computer, then start the game through steam.
It displays a black screen with some yellow description. I didn't do anything, and the game is trying to switch to fullscreen - it crashes.
[dinput8.log](https://github.com/Kaldaien/FAR/files/1844746/dinput8.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1844747/modules.log)
crash.log - empty

I didn't give up. I've tried to read the log myself, but I didn't find anything useful myself. I've deleted the log folder and start the game again. This time it goes fullscreen successfully and shows the "YoRHa" loading screen, but before it displays the title, it crashes. I've also tried to open the GUI, and it works.
[dinput8.log](https://github.com/Kaldaien/FAR/files/1844750/dinput8.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1844754/modules.log)
crash.log - empty

thank you for your time reading this.

**Comment by Idearum** [comment]
> 03/24/2018 20:59:25.714: [ Module ]  ( 0000000180000000h + 07368704 )   -:< _DllMainCRTStartup                                               >:-   G:\Steam\steamapps\common\NieRAutomata\dinput8.dll
 ----------------------  [File Ver]    Special K Modding System  0.8.25

You've installed an old version of FAR. Install the latest v0.7.0.23. It should be reported as "Special K Modding System 0.8.60.1" in the modules.log file afterwards: https://github.com/Kaldaien/FAR/releases/download/far_070/FAR_0_7_0_23.7z

Hopefully that solves it.

**Comment by apflu** [comment]
Well... Well met my friend... Not sure if you are also glad to see me again xD

But I really come back again. I'm sorry that I didn't see the notifications for days, so I didn't respond in time.

> It should be reported as "Special K Modding System 0.8.60.1" in the modules.log file

I've installed the latest mod, and I've checked out the file mentioned above. It displays properly.
After I enter the game, some strange words(english anyway) flashes on the top of the game window, but it's too fast that I can't see it properly. And the game crashes. I was busy trying to make a screen capture, but I failed. And it's a pity that I can't make it happen again. After that launch the game instantly crashes without display any window to me.
After startup I can see it in Task Manager for a few seconds, and then it quits.
===logs===
[crash.log](https://github.com/Kaldaien/FAR/files/1859523/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1859524/dinput8.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/1859525/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1859526/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1859527/steam_api.log)

Oh yeah, I've nearly forgot a detail.
I've "updated" a pirate version game to steam version(move it into the right position and make steam do the installation). I don't know if that will make anything wrong, but after a few GB downloading all the files seems good. I've verified all the files again, and no further downloads appeared. In the UI from FAR I've seen the description "I am not a pirate!" once before.

Thank you for your time reading this and your help.

**Comment by apflu** [comment]
Yes! I've got the screen shot.
![image](https://user-images.githubusercontent.com/25970844/38083826-06a2ba3e-334b-11e8-9da9-690d0f4b94b9.png)
Hmm... Maybe I've heard someone talked that time. I couldn't hear it clearly.

**Comment by Idearum** [comment]
Something is really weird with your system, as I've never seen those types of crashes before. For example, there's no reason why the below should even be possible unless you've enabled a bunch of resource monitors in the mod before:

> 03/29/2018 12:15:50.401: [-(Source)-] [!] {             dinput8.dll}                                              SK_WMI_ServerThread  <c:\users\andon\source\repos\specialk\src\io_monitor.cpp:193> 

Similarly, there's no real reason why the SK_CreateINI function would crash either.

I highly recommend you do the following in an attempt to solve the issue:

* Remove your My Documents\My Mods\SpecialK folder. This will remove all global settings for FAR as well as the global injector of Special K (another non-game-specific version of Kaldaien's mod/framework Special K).

* Ensure that NieRAutomata\Version\installed.ini is set to the following:

```
[Version.Local]
InstallPackage=FAR_0_7_0_23,24
Branch=Latest

[Update.User]
Frequency=never
KeepDownloads=true
BackupFiles=false
```

* Ensure that the game is excluded from your antivirus protection, and that there's no third-party stuff preventing access to your My Documents folder (OneDrive set to sync documents to "OneDrive" is known to interfere, as well as Google Drive Backup And Sync configured to backup the Documents folder from the computer, etc).

**Comment by Idearum** [comment]
If that doesn't solve it then I don't know what will. As I mentioned I've never seen these types of crashes you're experiencing before, so all I can say is that it's either your system being really weird, or a third-party application/tool/feature/protection/whatever causing issues with it.

**Comment by apflu** [comment]
Hi, thank you for your replies. It must take a long painful time to read my log file xD
Thank you for that.

Currently I'm trying to use those methods mentioned above. All files from the game checked out - successful.
A interesting fact is, I've found that there are... well, 5... 8... 12... 14... 16 "Microsoft Visual C++" installed in my computer. They are different versions since 2005. Don't know if that's really a problem, but I'll remove most of them anyway.

And here's my NieRAutomata\Version\installed.ini
`[Version.Local]
InstallPackage= 
Branch=Latest

[Update.User]
Frequency=never
`

hmm. Interesting, right? 
Anyway I'll try it now. I've disabled a lot of services once before, but nothing important I think. I will also check it out.
...Or I must learn C++ and try to read the code. Hope I don't need to do that! Terrible.

**Comment by Idearum** [comment]
> A interesting fact is, I've found that there are... well, 5... 8... 12... 14... 16 "Microsoft Visual C++" installed in my computer. They are different versions since 2005. Don't know if that's really a problem, but I'll remove most of them anyway.

Don't. They're needed for various applications on your system. Each "year" of the Visual C++ Redist is relevant for at least one of the applications on your system, although the 2015 and 2017 versions are interchangeable for the most part (which is why you can uninstall 2015 and install 2017).

The rest of them, however, is not backwards compatible and removing 2005, 2008, 2010, 2012, 2013, etc will most likely result in one or more applications on your system to be unusable until you reinstall that corresponding version.

That said, only the latest version of each architecture (x86 / x64) is needed for each "year," so if you've got two 2010 x64 redists you're free to uninstall the older x64 version. Just be sure to retain at least one of each architecture, meaning i.e. one 2010 x64 and one 2010 x86, and so on and so forth for each year.

For example, here's my own list of installed Visual C++ redists.

**Comment by apflu** [comment]
oh, no. I'm kinda too quick. No problem, I can install them back.
C++ learner is incoming and will not fail.

**Comment by Kaldaien** [comment]
I sincerely apologize, I never ever look at GitHub issue tracker. I see you put a lot of effort into this, and I feel like an ass ;)

I try to offer all my support on the Steam forums.


I have looked at your logs and these three things concern me:

```
03/29/2018 12:15:21.629: [ Module ]  ( 000007FEFCB00000h + 00196608 )   -:< nvCoprocThunk                                                    >:-   C:\Windows\system32\nvinitx.dll
03/29/2018 12:15:21.629: [File Ver]    NVIDIA shim initialization dll, Version 388.71   23.21.13.8871

03/29/2018 12:15:21.629: [ Module ]  ( 00000000737E0000h + 00024576 )   -:< Detoured                                                         >:-   C:\Program Files\NVIDIA Corporation\CoProcManager\detoured.dll

03/29/2018 12:15:21.629: [ Module ]  ( 000007FEFA020000h + 00229376 )   -:< setDeviceHandle                                                  >:-   C:\Program Files\NVIDIA Corporation\CoProcManager\nvd3d9wrapx.dll
03/29/2018 12:15:21.629: [File Ver]    NVIDIA d3d9wrap dll, Version 388.71   23.21.13.8871

03/29/2018 12:15:21.629: [ Module ]  ( 000007FEF9FF0000h + 00147456 )   -:< initialise                                                       >:-   C:\Program Files\NVIDIA Corporation\CoProcManager\nvdxgiwrapx.dll
03/29/2018 12:15:21.629: [File Ver]    NVIDIA dxgiwrap dll, Version 388.71   23.21.13.8871
````

Largely because I have no idea what those are. They really don't have any business showing up in these logs though. I would try disabling any NVIDIA enhancements you may have.

**Comment by apflu** [comment]
Oh what did i see! Kaldaien! It's glad for me to see you there. I'm kinda excited, well... xD

There's nothing to apologize, and what I have done is much smaller than you.

(*cough*) Let's come back to the issue. 

> NVIDIA + Intel co-existence

Yes! That is exactly what I dealing with. 

> And pull SpecialK64.dll out of it and replace the mod's dinput8.dll using that, things will proceed correctly.

I can hardly believe my eyes! I've successfully entered the game, everything works out! Thank you very much.

Btw this project is such wonderful for my wooden laptop! I thank you for writing this mod, or I must suffer under low FPS xD

I'll force it to use my NVIDIA GPU. Thanks for all the efforts from both Idearum and you.
