### ISSUE TITLE
unable to bring up FAR overlay in game

### ISSUE THREAD

**Issue by llisper** [Kaldaien/FAR#124]
thanks for providing this amazing mod!

When game is loading, I can bring up FAR overlay by pressing the corresponding keys. After the game has finished loading and the main menu is showed, I can't bring up FAR overlay, strangely I can't bring up steam overlay either. I'm pretty sure FAR is working because the resolution problem is fixed. very appreciated if you take the time to look at this problem :)

this is when the game is loading, FAR overlay is working at this time
![1](https://user-images.githubusercontent.com/2942231/37859550-75218d40-2f50-11e8-9c1e-c418f8a49789.png)

**Comment by Idearum** [comment]
1) FAR 0.7.0.1 is quite outdated. Latest is 0.7.0.23 - https://github.com/Kaldaien/FAR/releases/download/far_070/FAR_0_7_0_23.7z

2) If the newer version of FAR doesn't solve it then something is preventing the input keys from working properly post-loading. Start closing down third-party stuff until it starts working.
