### ISSUE TITLE
Crash after launch game.

### ISSUE THREAD

**Issue by Cielos** [Kaldaien/FAR#125]
[03-24-2018__21'20'40.zip](https://github.com/Kaldaien/FAR/files/1845014/03-24-2018__21.20.40.zip)

If I turn off EnableCEGUI option to false, game was launching fine. But, I want to see CEGUI menu. So, I followed your instruction below at #119 Issues.

> What you could also do is download this archive: https://github.com/Kaldaien/FAR/releases/download/far_070/FAR.7z and extract only the CEGUI folder contained within to the game folder, and see if that solves it (you'll have to change EnableCEGUI back to true). Latest version of the mod have CEGUI embedded within itself, which might be responsible for the crash.

> If that have no effect then it's almost certainly a third-party tool or application causing it, and you should probably start exiting/shutting down running stuff until you find what's causing it.

But Still not launching my games. I upload attachment crash log.

ps 1, It is steam version, not pirate version.

**Comment by Idearum** [comment]
Could you uninstall the Visual C++ 2015 and 2017 redistributables (both x64 and x86) from your computer and then reinstall the latest 2017 ones?

x64: https://go.microsoft.com/fwlink/?LinkId=746572 (direct download)
x86: https://go.microsoft.com/fwlink/?LinkId=746571 (direct download)

I am not certain this will fix it, but it it s the only thing I can think of as the crash.log file indicates an error in a VC++ related function.
