### ISSUE TITLE
Nier Autama FAR Mod not compatible with Wallpaper engine.

### ISSUE THREAD

**Issue by Koraiii** [Kaldaien/FAR#126]
This Mod worked really well but I had to uninstall it due to the fact that it kept on making my wallpaper engine crash. 

I spoke to a Developer of wallpaper engine called "Biohazard" and he said:

"Yes I know, because it does not ignore Wallpaper Engine. It hacks into it with a bad DLL, it must not do that.

Could you post on their forums so they can simply blacklist this program to stop crashing it?"

**Comment by Idearum** [comment]
The FAR mod is a local install of Special K and can not affect any other games or applications. If it did, then you did not install FAR, but instead mistakenly installed the global injector of Special K.

So there's two solutions here:

* Install FAR properly by running the automated installer, **>>changing the selected product to FAR<<**, and then click Install.

* Disable injection for Wallpaper Engine for the global injector of Special K by creating empty files named properly within Wallpaper Engine's folders:

  * Steam\steamapps\common\wallpaper_engine\SpecialK.deny.wallpaper32
  * Steam\steamapps\common\wallpaper_engine\SpecialK.deny.wallpaper64
  * Steam\steamapps\common\wallpaper_engine\bin\SpecialK.deny.ui32

  The above will properly disable injection for Wallpaper Engine's "wallpaper32/64" and "ui32" executables, and should be all that's needed.

**Comment by leons2525** [comment]
> The FAR mod is a local install of Special K and can not affect any other games or applications. If it did, then you did not install FAR, but instead mistakenly installed the global injector of Special K.
> 
> So there's two solutions here:
> 
> * Install FAR properly by running the automated installer, **>>changing the selected product to FAR<<**, and then click Install.
> * Disable injection for Wallpaper Engine for the global injector of Special K by creating empty files named properly within Wallpaper Engine's folders:
>   
>   * Steam\steamapps\common\wallpaper_engine\SpecialK.deny.wallpaper32
>   * Steam\steamapps\common\wallpaper_engine\SpecialK.deny.wallpaper64
>   * Steam\steamapps\common\wallpaper_engine\bin\SpecialK.deny.ui32
> 
> The above will properly disable injection for Wallpaper Engine's "wallpaper32/64" and "ui32" executables, and should be all that's needed.
> 
> Edit: Suffice to say I highly recommend installing FAR properly instead of relying on the global injector of Special K. The global injector is exactly that, >>global<<, and it affects basically all Steam games/applications that uses your GPU, meaning it can also inject itself into multiplayer games and potentially cause issues that you do not want.

How do I fully deleted special k or FAR of my computer? I installed far for nier atomata but I guess I installed special k, I want to get fully rid of it but I have no idea how.
