### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Alalai79** [Kaldaien/FAR#128]
[crash.log](https://github.com/Kaldaien/FAR/files/1886627/crash.log)

![image](https://user-images.githubusercontent.com/38164752/38458623-ae6d3efe-3aa0-11e8-9aa5-c5689c6f8524.png)

at startup crash. Only one that i see that a white window named Nier automata

**Comment by Idearum** [comment]
Please post your dinput8.log and modules.log as well.

**Comment by Alalai79** [comment]
[dinput8.log](https://github.com/Kaldaien/FAR/files/1887130/dinput8.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1887132/modules.log)

**Comment by Alalai79** [comment]
ok. Thank you)

**Comment by keyserjaya** [comment]
Fair enough :D
