### ISSUE TITLE
FAR menu invisible/not working

### ISSUE THREAD

**Issue by blazej222** [Kaldaien/FAR#130]
Hi! I installed the latest version of FAR mod using auto-installer, and I can see my game's resolution changed a little bit. The problem is,  I can't get menu to work. When I press Ctrl+Shift+Backspace, my mouse goes to upper left screen corner and my keyboard stops working until I press that combination again. Also, my mouse stops working on certain screen area, so it's just like the window was here, but invisible. I have disabled Discord and every program that could interfere with the mod. I also don't see mod's banner when the game starts.
Here are my logs: 
Dinput8.log : https://pastebin.com/UwwgQ7Y1
Modules.log : https://pastebin.com/WbRZSCJZ
I'm using 2 monitors, but when I disconnect one of them it just doesn't change anything.
How can I get menu to work?
Thanks in advance

@Edit Just checked, menu works perfectly on all versions containing CEGUI folder, doesn't work on versions that don't contain that folder

**Comment by stomachblope** [comment]
this happened to me to, the mouse just goes into the topleft corner. i have the CEGUI folder, too. help??

**Comment by sc0rch** [comment]
I fixed this issue by copying CEGUI folder from FAR.7z (without version).
It is really unintuitive, dunno, it should be a part of auto-install process.
