### ISSUE TITLE
Can't accept the terms of condition

### ISSUE THREAD

**Issue by zerokn** [Kaldaien/FAR#131]
i don't see any button or something to accept the terms, what to do? wh

**Comment by Idearum** [comment]
If you own the game on Steam, do a game file validation as you seem to have a corrupt steam_api64.dll file. If you don't own it, buy the game? :)

That accept button performs, as I mentioned, a validation of the steam_api64.dll file, and it it doesn't match the one on record it will simply not allow you to accept the terms. 🤷‍♂️

**Comment by zerokn** [comment]
I have the original from steam, but I checked and reinstalled but it doesn't appear, till what version it checks the steam api?

**Comment by Idearum** [comment]
Upload the modules.log and dinput8.log from the logs subfolder of your game to pastebin.com and link them here and I'll see if I can spot what's causing the issue.

**Comment by zerokn** [comment]
thanks, i would.
