### ISSUE TITLE
Nier Automata random crashes, mostly when loading new zones

### ISSUE THREAD

**Issue by CoolGiraffe** [Kaldaien/FAR#133]
First of all, Thanks for the great mod =]
After days of searching for a solution I ended up coming here for help.
I keep getting random crashes to desktop without any sound or freeze (just sudden crash), usually when walking into a different area or between two zones.
It happens every 15 minutes or so, depending on how much I travel around.

I tried pretty much every solution online and nothing helped:

-Installed older driver ( 378.66-x64 Nvidia gpu), Fixed the white screen issue I was having but still crashing.
-Installed newest driver (made the game crash at loading, barely working)
-Setting core affinity to disable hyperthreading.
-Closing every third-party app (except steam ofc) and disabling steam overlay.
-Fiddling with gpu driver settings.
-Tried the game on both ssd and hdd.
-Tried lowering Texture Caching size in FAR settings.
-Setting global lighting to medium/off.
-Reinstalling the mod.

my specs:
Intel Core i5 3550
8G ram
GeForce GTX 1060 6GB
SSD

crash logs:
[CEGUI.log](https://github.com/Kaldaien/FAR/files/2153100/CEGUI.log)
[crash.log](https://github.com/Kaldaien/FAR/files/2153101/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/2153102/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/2153103/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/2153104/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/2153105/modules.log)

also, heres another crash log which seems different, both behaved the same though:

[CEGUI.log](https://github.com/Kaldaien/FAR/files/2153107/CEGUI.log)
[crash.log](https://github.com/Kaldaien/FAR/files/2153108/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/2153109/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/2153110/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/2153111/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/2153112/modules.log)

I really hope I provided enough info,  any help would be very appreciated!

**Comment by Idearum** [comment]
The crash logs indicate that it's related to XAudio2Create, which is a function to create or play some type of audio, I imagine.

Have you [verified game files through Steam](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335) ? It wouldn't surprise me if you had a corrupt audio file in the game folder that causes the game to crash when it tries to play it.

**Comment by CoolGiraffe** [comment]
I verified the game files and also deleted the FAR folder from "My Documents" folder to let it add itself again.
Been playing for 2 hours now without any crashes, It does stutter quite a bit but I don't mind that at all.

So I think it did the trick! Thank you so much!, i'll update if the problem occurs again.

**Comment by apflu** [comment]
Maybe try not to install a game in "C:\Program Files (x86)\", system-protected folder always issue new random questions.

Btw 1066 should be able to run without this mod, have you ever tried? If your game also crashes, then it shouldn't be the problem about this mod.
