### ISSUE TITLE
HD Textures not working with 'Bande Desinee' installed

### ISSUE THREAD

**Issue by AikoTM** [Kaldaien/FAR#137]
Should be a pretty known issue - couldn't find any fix for it though.
Does anybody have an idea how to get this working?

Basically when you have FAR installed and the HD Pack from Nexus, but then install Bande Desinee, the HD textures stop working. 

Bande Desinee: [LINK](https://www.nexusmods.com/nierautomata/mods/1)
HD Pack: [LINK](https://www.nexusmods.com/nierautomata/mods/5)

**Comment by CreeperLava** [comment]
I second this. I tried 2 versions of FAR :
- 7.0.23 is as detailed in the issue report, texture injection doesn't work with Bande Dessinee's d3d11 dll
- Using 7.0.24 with Bande Dessinee results in game crash

**Comment by soredake** [comment]
@Kaldaien
