### ISSUE TITLE
Game doesn't start with dinput8.dll

### ISSUE THREAD

**Issue by RedFame01** [Kaldaien/FAR#140]
Hi, when I install the mod, the game doesn't start. I tried the version 0.7.0.20 0.70.0.23 and the don't work. I also tried the version 0.7.0.14 that break explorer.exe (when i'm going to copy some files  the speed is 200 byte for second and i don't know why. Btw my game is cracked (cracked-games.org) could this be the problem? Thank you

**Comment by apflu** [comment]
The game surely work without the mod. None forced you to use this mod.
The author seems not going to support the pirate version. If you are unsatisfied with the game, request refund on steam.
