### ISSUE TITLE
If dinput8 file setting to EnableCEGUI=true, crashed game.

### ISSUE THREAD

**Issue by Nidruno** [Kaldaien/FAR#143]
I follow this solution, https://github.com/Kaldaien/FAR/issues/125#issue-308321512
But i still crashed game if dinput8 file setting to EnableCEGUI=true.

[crash.log](https://github.com/Kaldaien/FAR/files/2633074/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/2633075/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/2633076/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/2633077/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/2633078/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/2633079/steam_api.log)

**Comment by Idearum** [comment]
Avast is hooking the game. Have you tried disabling its Game Mode-thingy? I believe that might be what's hooking the game at least.

If that doesn't work, and you don't use any other Special K mods then I'd recommend trying out removing the Documents\My Mods\Special K folder and seeing if that has an effect on the issue.

**Comment by Nidruno** [comment]
I deleted Documents\My Mods\Special K folder, finally solved this problem.
I appreciate you taking the time. thank you.
