### ISSUE TITLE
bought the game - can't click accept

### ISSUE THREAD

**Issue by telrunya** [Kaldaien/FAR#146]
Good afternoon,

I bought Nier Automata yesterday evening and read that i could install the FAR mod to fix some issues.
So i installed the "Special K" thing, and launched the game, pressed the keys to open the mod and i couldn't click accept, nor with the gamepad I use or the keyboard. The mod also made my game crash a lot, i couldn't alt-tab out etc..
I really want to clarify that i BOUGHT the game for 25 euros, i bought it on a french website equivalent to G2Deals etc, i bought the key, installed it on steam and everything runs perfectly. Why would this be considered a pirate version by your mod? Or did I install the mod wrong ?

**Comment by telrunya** [comment]
![image](https://user-images.githubusercontent.com/48182299/53701268-77f2d780-3dfb-11e9-8dee-c4f684565718.png)
A little update, i tried installing the mod again, I can't bring up the mod menu with ctrl+shift+space, only with my gamepad. The task manager instantly says when i launch the game with the mod that the game isn't responding, i have to force close it.
I randomly mashed buttons of my gamepad and i managed to click on accept but my mouse doesn't respond on the mod menu and i can't click on anything it just won't let me. I joined a picture of what i get. Thank you in advance for any replies

**Comment by Idearum** [comment]
Third-party conflict of some kind. Please upload your dinput8.log and modules.log from the logs subfolder here and I'll see if I can identify what's causing it.
