### ISSUE TITLE
1920x1080 on an Ultrawide screen

### ISSUE THREAD

**Issue by RitzyBusiness** [Kaldaien/FAR#15]
Since I would rather not play with stretched cutscene moments I was wondering if anyone was able to get this resolution to work properly on fullscreen with this mod.

While running this mod rather then letting my GPU aspect correct it the mod stretches the image out.

**Comment by Kaldaien** [comment]
Change `Scaling=` to ***Centered*** in `dxgi.ini`, and that should resolve the problem.

**Comment by RitzyBusiness** [comment]
that did it~
