### ISSUE TITLE
missing dlls for the game to launch

### ISSUE THREAD

**Issue by mustang7er** [Kaldaien/FAR#152]
MSVCP140.dll 
CONCRT140.dll 
VCOMP140.dll 
VCRUNTIME140.dll 
Missing these 4 dlls, I resently reinstalled my windows 10, not sure what runtime enviroment I'm missing. The game can launch properly without the mod, but the mod can't stard.

**Comment by Idearum** [comment]
https://pcgamingwiki.com/wiki/Special_K#System_requirements

**Comment by mustang7er** [comment]
> https://pcgamingwiki.com/wiki/Special_K#System_requirements
> 
> Those are all files that's a part of the Visual C++ redist package

thanks！
