### ISSUE TITLE
CPU monitoring not working

### ISSUE THREAD

**Issue by ceedveed** [Kaldaien/FAR#153]
Does anyone else have this issue?

I start CPU monitoring for the OSD and it remain stating "Starting CPU Monitor..." I waited 30 minutes.

**Comment by Idearum** [comment]
Restart the game and it should work. If it doesn't, there's probably an issue with the WMI subsystem of Windows, which is what that monitor tries to make use of.

**Comment by ceedveed** [comment]
I have two systems, A and B:

A) Windows 10 1809 can display CPU monitoring with 0.7.0.22. B) Windows 10 1803 can display CPU monitoring only with 0.7.0.7 and below (not all tested).

So I solved this issue by using older versions.
