### ISSUE TITLE
Hello   The White Screen Issue  0.7.23 ver

### ISSUE THREAD

**Issue by KoreanUser1** [Kaldaien/FAR#157]
i'm korean   I am currently using a translator.

I tried to use Far, but the white screen appears.

I'll attach the relevant crash log.
[
[game_output.log](https://github.com/Kaldaien/FAR/files/3963435/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/3963436/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/3963437/steam_api.log)
[crash.log](https://github.com/Kaldaien/FAR/files/3963438/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/3963439/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/3963440/dxgi_budget.log)
[modules.log](https://github.com/Kaldaien/FAR/files/3963441/modules.log)

**Comment by KoreanUser1** [comment]
I'm not sure what kind of file I need. If there's anything missing, I need you to let me know

**Comment by KoreanUser1** [comment]
Currently 0.6.X is operational, but mode is not applied

**Comment by Andralee0698** [comment]
안녕하세요 혹시 해결 못하셨으면 연락 주세요 카톡 blackrun0698
