### ISSUE TITLE
Changes are not saved.

### ISSUE THREAD

**Issue by Mokalyn** [Kaldaien/FAR#158]
Hello!

My problem is quite simple: I am using FAR MOD 7.014 and it worked perfectly, however I wanted to change a few things like the light from ULTRA to HIGH and activate the Bloom and AO from default to Native, but!

When restarting the game, the options are again by default (Ultra and Bloom and AO default).

Why are not changes made to me?

FAR MOD 7.015 to 7.023 does not work for me. I don't understand the reason, my Nier just doesn't open, it stays on white screen.

(My Nier is a legal copy, Steam's gift this Christmas).

Regards!

**Comment by Idearum** [comment]
What resolution are you playing at?

**Comment by Mokalyn** [comment]
1600x900, thats my native screen resolution. IN GAME its the same: 1600x900, Fullscreen. 

But i dont have any problem with the resolution.

**Comment by Idearum** [comment]
That's why. Default resolution for Ambient Occlusion and Bloom is optimized to 1600x900, and so there's no difference between Native and Default for you. They're both the same.

**Comment by Mokalyn** [comment]
Oh, understood. Thanks you.  

A extra question aside this, i suffer 3 crash Vs the Opera Singer Boss, well, its not exactly a crash, the game only ... close, without error log or something. 

Its normal? i thinking its because the overload of effect (balls, rays, etc). Any "tips" from FAR 0.7.14 i can change to minimize this? 

My configuration:
1600x900 full screen, Anti-Aliasing OFF, AO ON, Texture filtering x8, blurr OFF, Shadow Medium, **Effect HIGH**. 

Effects are only effects from attack? or include environment effects?

Thank you again for you helping!

**Comment by Idearum** [comment]
No, that sort of issue aren't normal. I recommend you validate game files on Steam to ensure that you do not have any corrupt data files.

**Comment by Mokalyn** [comment]
Thank you.
