### ISSUE TITLE
Can't use WQHD (1440p) resolution

### ISSUE THREAD

**Issue by VADS** [Kaldaien/FAR#159]
No matter what I try, even though I set the resolution to 2560x1440 in FAR, I can't seem to get the game to render in 1440p. It always either renders too small (FHD) or way too big (4K) - I also noticed that theres no 1440p option in the game's settings, but I thought FAR was the way around it.

I'm also getting some visual artifacts with the FAR GUI - any ideas? Do you need any log files or something? With my old FHD monitor, everything worked fine but since I've gotten this new 1440p display, I couldn't get it to work anymore.

![image](https://user-images.githubusercontent.com/1810902/73118554-feedf880-3f55-11ea-9d13-89a3dfa96855.png)

**Comment by Idearum** [comment]
Remove dxgi.ini and FAR.ini to reset the settings of the mod entirely, then use the in-game settings menu of the game itself to select 2560x1440 as the resolution.

If the 2560x1440 resolution doesn't appear in the game's own settings menu then there's some other issue you're experiencing, as that shouldn't happen. This game exposes basically all resolutions that the monitor specifies that it supports.

**Comment by VADS** [comment]
I couldn't find a dxgi.ini, but I deleted the far config and tried again, but I still can't select that resolution:

Is there anything else that could be misconfigured? Thanks for your quick answer :)

![image](https://user-images.githubusercontent.com/1810902/73128230-6e063400-3fcc-11ea-86af-954a65b3de4e.png)

**Comment by Idearum** [comment]
Right, on FAR the config file is called "dinput8.ini" instead of dxgi.ini.

As for why 2560x1440 doesn't appear, I'm not entirely certain. I've played the game on multiple 1440p monitors and have never experienced that.

Are you sure that the resolution appears in Windows' display resolution menu as well? And that you do not have a second monitor attached that might screw up with it?

**Comment by VADS** [comment]
What a weird bug that was. I disconnected my second FHD screen, then I could select 1440p as a resolution. I now even have the second monitor connected again and it still works fine. Very strange. Thanks for your help and this awesome mod :)
