### ISSUE TITLE
Auto-Updater Popup Cannot Be Interacted With

### ISSUE THREAD

**Issue by SK83RJOSH** [Kaldaien/FAR#16]
I'm getting the SpecialK auto-updater window each time I launch the game, and I'm unable to click "Update" or "Remind Me Later". I'm also unable to interact with ANY thing in general until I kill NieR with task manager.

Additional Details: I have FAR configured to force borderless mode, and to center the window.

**Comment by Kaldaien** [comment]
Press space bar. Or do a manual uninstall and re-install with SKIM64.

Centering the window is flaky, just so you know. That may prevent resolution changes in-game. If you intend to always run the game at a certain resolution and want to use the center + borderless feature, I would suggest setting OverrideRes=...

**Comment by SK83RJOSH** [comment]
Yeah I noticed the resolution was a bit finicky, and I also tried spacebar
/ enter and had no luck. I had to disable borderless in my config so I
could update ultimately. 😛
