### ISSUE TITLE
[v0.7.0] Poor Performance w/ Navi GPU

### ISSUE THREAD

**Issue by Jpec07** [Kaldaien/FAR#160]
While using a Navi GPU, in this case the RX 5700 XT, I am encountering some performance issues using FAR.

When I play the game without the mod, I am able to achieve 60fps at almost all times. However, when I install the mod, I find myself getting 15-20fps at maximum (with some more stressful renders dropping down to below 10fps). Attempting an overclock of my CPU brought my FPS up slightly, which leads me to believe that something in this mod does not recognize the Navi GPU, and so is attempting to render the game on the CPU.

I would attempt a pull request to resolve this issue, but I'm not even sure where to begin looking in the code. With a little guidance, I'd be willing to contribute.

**Comment by richwalm** [comment]
I'm not sure if you're still having this issue, but I also have a 5700XT and the game runs fine for me. Using driver 20.9.2.
