### ISSUE TITLE
Game crashes when loading save

### ISSUE THREAD

**Issue by ShaharShtern** [Kaldaien/FAR#161]
Bought the game yesterday but it would crash when I tried to launch new game. I managed to fix it and played for an hour. Today I launched the game and again it crashes when I try to load my save and no matter what I can't fix it.
I tried
-Reinstalling the game
-Verifying files
-Disabling antivirus
-Reinstalling c++ Redistributables
-Launching with and without FAR
-Deleting my save and starting new
-Changing settings in FAR
-Change CPU affinity

[CEGUI.log](https://github.com/Kaldaien/FAR/files/4270353/CEGUI.log)
[crash.log](https://github.com/Kaldaien/FAR/files/4270355/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/4270356/dinput8.log)
[dxgi_budget.log](https://github.com/Kaldaien/FAR/files/4270357/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/FAR/files/4270358/game_output.log)
[modules.log](https://github.com/Kaldaien/FAR/files/4270359/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/4270360/steam_api.log)

**Comment by Kindail** [comment]
It seems that turning off my second monitor fixed this for now
