### ISSUE TITLE
Cap FPS during hacking minigame

### ISSUE THREAD

**Issue by Francesco149** [Kaldaien/FAR#17]
during the hacking minigame, FPS needs to be capped.
the flag 0x1410E0AB4 can be used to check similarly to the ones used for menus.

EDIT: there's also 0x1413FC35C for the shortcuts menu.

**Comment by Kaldaien** [comment]
This is great, thank you.

Do you think you could also find the memory address that controls whether quicksaving is allowed? Arbitrary quicksave support would help people with the whitescreen problem.

I'm no good at hunting and pecking for this stuff but you seem to have a knack for it :)

**Comment by Kaldaien** [comment]
By the way, I notice your Reddit username is different than GitHub.

I would like to credit you for finding the gamestate addresses because they're much more important than you're giving yourself credit for. But I don't know how to address you.

**Comment by Francesco149** [comment]
You can credit my github username, and I will take a look for the addr.

**Comment by Francesco149** [comment]
eh, I debugged the game for a bit but the quicksave toggle is either complex or obfuscated. couldn't find a simple toggle for it nor some kind of nearest access point id value.

I did find a function that handles choices in the pause menu, but I couldn't figure out how to unlock the quick save button.

if you find someone who can actually reverse properly they will probably find it
