### ISSUE TITLE
how do you uninstall this?

### ISSUE THREAD

**Issue by MelonBreadVR** [Kaldaien/FAR#172]
any instructions on how to uninstall this? It's conflicting with my Steam VR

**Comment by Idearum** [comment]
> any instructions on how to uninstall this? It's conflicting with my Steam VR

FAR shouldn't conflict or even affect anything outside of NieR: Automata. You've probably mistakenly installed the global injector of SKIM. To uninstall that one, you need to run SKIM from the start menu (I believe it can be found under Special K) or from Documents\My Mods\SpecialK\SKIM64.exe. Then hit "Uninstall" when the product is set to "Global Injector" and that should take care of it.
