### ISSUE TITLE
Is this still usefull?

### ISSUE THREAD

**Issue by Xapu1337** [Kaldaien/FAR#173]
As of the 15/07/2021 most things that FAR provided had been added. This includes:
Borderless Video Settings
HDR
Anti-Aliasing 
UI Textures rework (made them all 4k)
GI Settings (HIGH, MEDIUM, LOW)
And Ambient Occlusion and Bloom target the game resolution.

Seems like some features are still useful to have since FAR has a wider range of GI Settings
but it looks like some features might be obsolete.

**Comment by radjah** [comment]
And game crash with latest version of FAR. :(

**Comment by Idearum** [comment]
Kaldaien have lost access to this GitHub account, so don’t expect any changes here.

As for FAR (aka Special K), older versions kept in this repository is not compatible, and needs to be removed. Newer versions work, though in a limited fashion (basically no NieR: Automata tweaks works).

For now Special K (aka FAR) is limited to its general-purpose improvements and features, such as texture injection, FPS limiter, etc.

I recommend checking out the official page for NieR: Automata over on the Special K wiki:

https://wiki.special-k.info/SpecialK/Custom/FAR

**Comment by oOtroyOo** [comment]
I noticed that NierR has a huge 16GB updates. 
I konw it probaly has some issues with thrid party patches  ,before updates. I just removed game ,and re installed it .
I found that the game is now supprots native 1080p, but still locked frame at 60, that makes my screen(144hz) tears if vsync off.
so waiting any patchs of FAR..

**Comment by Idearum** [comment]
> I noticed that NierR has a huge 16GB updates.
> I konw it probaly has some issues with thrid party patches ,before updates. I just removed game ,and re installed it .
> I found that the game is now supprots native 1080p, but still locked frame at 60, that makes my screen(144hz) tears if vsync off.
> so waiting any patchs of FAR..

Special K (aka FAR) have been updated and supports some features for the game already. While an FPS unlocker still isn’t available, Special K will at least allow you to run the game at v-synced 144 Hz refresh rate, though if you’re on Windows 10 I recommend using the borderless mode since it’s basically identical to the Fullscreen mode in terms of performance.

**Comment by oOtroyOo** [comment]
Great, I tried now. It works fine. supports high FPS  .

**Comment by kamikazilucas** [comment]
idgi im using the new version of nier but turning global illumination to low barely gets me any more fps

**Comment by Aemony** [comment]
> idgi im using the new version of nier but turning global illumination to low barely gets me any more fps

Game's own "GI Low" resides somewhere between SK's "High" and "Medium" setting.

Set the game's own global illumination toggle to "High", then use SK's override to set it to Medium or below -- any would give you a higher performance boost than having the game's own setting set to "Low".

**Comment by kamikazilucas** [comment]
> > idgi im using the new version of nier but turning global illumination to low barely gets me any more fps
> 
> Game's own "GI Low" resides somewhere between SK's "High" and "Medium" setting.
> 
> Set the game's own global illumination toggle to "High", then use SK's override to set it to Medium or below -- any would give you a higher performance boost than having the game's own setting set to "Low".

ok i will set the sk to low and then gi ingame to high then, i tried setting it to low now and im getting pmuch locked 60 now at 1080p so good
