### ISSUE TITLE
metal gear sound closes game

### ISSUE THREAD

**Issue by ChoriDesnudo** [Kaldaien/FAR#174]
i recently bought nier automata on steam, and installed FAR, but it only crashes the game or makes a metal gear sound and then it closes, what should i do?

**Comment by Gh0sTG0** [comment]
Hi. I'm not dev, but I'm here and have info:
There was an update on nier automata recently. Update that inserted ~all things that far was made for. I don't know if far will be updated, but for now... You can try to read this and maybe things you want to have will work (like texture injections, etc): https://www.nexusmods.com/nierautomata/mods/29 BTW there you can find about ~all things you can do with nier now. Maybe except some number of suits that changes only visual of 2b, etc. For them manually check description about latest update. It should be after jul 15 and have info about compability with new patch.

**Comment by Aemony** [comment]
Updated FAR (Special K) guide is here nowadays:

https://wiki.special-k.info/SpecialK/Custom/FAR

This version here on GitHub is not compatible with the latest version of the game and so cannot be used.
