### ISSUE TITLE
Achievement popup garbled

### ISSUE THREAD

**Issue by dobasy** [Kaldaien/FAR#18]
Maybe related to 2-byte characters?
I'm playing in Japanese.

![20170330110524_1](https://cloud.githubusercontent.com/assets/2500068/24484395/ef164790-1538-11e7-8517-f46541fba09d.jpg)

**Comment by Aoshi5180** [comment]
I am so sorry that I can't answer your question but can you tell me how to get this Special K control panel thing to pop up? I can't find anything. Sorry noob question.

**Comment by dobasy** [comment]
See this page:
http://steamcommunity.com/app/524220/discussions/0/135512104777399045/
Configuration Menu: Ctrl + Shift + Backspace

**Comment by Kaldaien** [comment]
This _may_ be fixed in the latest version, can you test the achievement lockup with 0.4.1.4? I know the game title works, but I do not know if the font I am using has support for Japanese characters.

**Comment by dobasy** [comment]
Corruption was fixed. Thank you.
As you mentioned, Japanese characters were not supported.
I made merged fonts (DejaVuSans + Subset IPAexGothic, Jura-DemiBold + IPAexMincho) and looks good, but maybe license issues?

![20170331113958_1](https://cloud.githubusercontent.com/assets/2500068/24534105/d3f52b1a-1606-11e7-9e24-995e1be62c16.jpg)
