### ISSUE TITLE
Resolution still broken when trying to play fullscreen at non-native resolutions of monitor

### ISSUE THREAD

**Issue by sriRacha21** [Kaldaien/FAR#2]
This mod does not fix the graphics issues at lower resolutions than the max resolution of your monitor.

**Comment by animegirl13** [comment]
I can confirm this. Trying to play at 1440p and fullscreen the game is rendering at a lower resolution on my 4k monitor

**Comment by Kaldaien** [comment]
This is probably caused by RivaTuner Statistics Server or some other third-party software.

If you could provide a copy of `logs/dxgi.log` and `logs/modules.log` I may be able to diagnose it.

**Comment by animegirl13** [comment]
It was fixed for me after 0.1.3.3 I believe but now even if I go back to a previous version I still can't reproduce it.
