### ISSUE TITLE
Ambient occlusion change breaks motion blur?

### ISSUE THREAD

**Issue by s-ilent** [Kaldaien/FAR#26]
It appears that the AO override breaks the motion blur. While the AO tweak is enabled, object motion blur seems to stop working properly.

[Example screenshot.](https://files.catbox.moe/td47ip.jpg)

It's a hard to see in the screenshot, but note that the tree is blurred while 9S is not. The lack of blur around objects is fairly noticeable in-game, but I didn't have much luck capturing a good shot of the out of place blurring. It's slightly more visible with higher resolutions.

**Comment by PeterTh** [comment]
Interesting. I'll have to investigate that.
