### ISSUE TITLE
SKIM64 installer doesn't work properly

### ISSUE THREAD

**Issue by mrskizzex** [Kaldaien/FAR#27]
Hello,
FAR works beautifully but i'm having some problems with installer. Mainly It seems like it doesn't know that it successfully installs the mod. If i delete the dxgi.dll it creates it and when i launch the game it works but i can't uninstall nor install beta version.

[Video showing the issue](https://my.mixtape.moe/jmdgas.webm)

EDIT: Global Special K also doesn't work. When I launched a game through Steam i got autoupdate popup and updated files but it doesn't seem to be loaded at all on subsequent launches. Hotkeys don't work and OSD doesn't show up. But when i hold Ctrl+Shift the compatibility popup shows up but when I press OK it just closes the game.

**Comment by Kaldaien** [comment]
Stop running the installer from the game directory, that's never going to work correctly.

To recover from that problem, delete the Version directory and then run it from somewhere else. It's designed to be downloaded when you need it and run directly from the web browser, so whatever temporary directory it puts it in is good.

**Comment by mrskizzex** [comment]
Your suggestions worked partially.
My firewall is not blocking anything because Global SpecialK [downloads just fine,](https://my.mixtape.moe/msynyu.webm) but running SKIM outside of the game directory (even though it worked correctly that way before) reveals this [error](http://i.imgur.com/gGflTlx.png).

I moved my game to different drive and this is probably the cause but I have no idea how to fix it because I don't know where it's pulling install dir from. Game was moved by simple Cut>Paste and then moving it's appmanifest to different steam library. Steam recognizes it normally and there was no symbolic links/junctions used.

Also regarding global Special K, is it possible to make it recognise Reshade64.dll like Far does ?

Thanks for fast response.

**Comment by Kaldaien** [comment]
Ah, I see. When you move games in Steam, there's a manifest file that determines the install location.

The only way it would be picking up the wrong location is if you had two manifests. My installer looks through all of the Steam libraries in your [b]libraryfolders.vdf[/b] file (the one in Program Files (x86)\Steam).

Globally, no. There is no way to make this apply to all of your games.

However, you can edit `%USERPROFILE%\Documents\My Mods\Profiles\_Name_Of_Game_\SpecialK.ini` and add the same ReShade64.dll lines that are in `dxgi.ini` with this mod. Do that on a game-by-game basis.

**Comment by mrskizzex** [comment]
It really was in two places. I was sure i moved it and not copied it, oh well. Thanks for help Kaldaien and keep up good work.
