### ISSUE TITLE
0.5.2.9 (or .8) breaks mouse in game

### ISSUE THREAD

**Issue by chrisp** [Kaldaien/FAR#31]
you can move the mouse pointer but mouse won't move the camera and mouse clicks don't register
(installed via steam)

**Comment by chrisp** [comment]
.8 seems to work fine for me - just .9 that is having the issue

**Comment by Kaldaien** [comment]
It should be fixed in 0.5.2.10. The game wasn't properly responding to device removed events, I've worked around it. Let me know if it's still giving you problems.

**Comment by chrisp** [comment]
thanks!
