### ISSUE TITLE
Locked at 60fps since 0.5.2

### ISSUE THREAD

**Issue by pikajude** [Kaldaien/FAR#34]
Steam overlay FPS counter shows 60 FPS, as does the FAR OSD in the top left, though it shows the actual FPS at the end of the same line (which varies between 60 and 300+ depending on what screen I'm on).

**Comment by Kaldaien** [comment]
That's how it's supposed to work. The framerate limiter is being disabled and re-enabled based on the game screen. You will need to fix your display settings, however, to get anything above 60 FPS.

**Comment by pikajude** [comment]
My display settings haven't changed since I ran 0.5.2. It's still set at 165Hz in the NVIDIA control panel.

**Comment by Kaldaien** [comment]
That doesn't matter, you have to set the refresh rate in the INI file, or the game will use 60 Hz.

**Comment by markni** [comment]
You'll need turn off V-sync in game.
