### ISSUE TITLE
Global Illumation Drop Down Menu Instantly Dissapears

### ISSUE THREAD

**Issue by Jacob29** [Kaldaien/FAR#35]
Title.

Click on the arrow, it goes down and then instantly back up again.

**Comment by Kaldaien** [comment]
I cannot reproduce this and I have no idea why it would happen either.

**Comment by Kesacoli** [comment]
I have this problem too, I can't use any drop down menu they just instantly pull up
It's on a fresh install of the game, I recently bought it I had done no modification to the game the first time I launched it and it was with FAR
i'm using Borderless gaming to make the game in borderless full screen maybe it's an issue ? 
(I tried to modifiy the settings in fullscreen without borderless gaming and it was still not working so I doubt it comes from here)

**Comment by Idearum** [comment]
@Kesacoli is pretty much correct. What seems to happen is that when you open the Global Illumination drop down menu the actual control panel window of FAR seems to get the focus, or is trying to be on-top of all the FAR windows in the overlay. Directly after the Software License Agreement window gets its "Always on Top" parameter reapplied which closes the drop down menu directly.

Solution? Accept the licensing agreement before tweaking the GI option.

**Comment by Kaldaien** [comment]
I see, I guess I could make that window modal (the correct way 😄).
