### ISSUE TITLE
Mouse is invisible in the menus

### ISSUE THREAD

**Issue by MemesterScreb** [Kaldaien/FAR#37]
I got an achievement and FAR gave me a popup. My controls locked up and were non-responsive. Every now and then a key press would register but that's it (a movement key for example D would register and lock up so the character would just keep on moving right). I could not get to the menu so I force-quit the game with alt+f4. When I restarted the game the mouse was invisible in menus. If you hover over the optionsvery quickly in the menu, right after the press any button one, you can see the mouse appear for a hundreth of a second . I tried the allways-show mouse option in FAR but then it also shows the mouse in game.

**Comment by Kaldaien** [comment]
Should be fixed now, this was another case of me trying to fix ReShade stuff after adding official support for ReShade....... and breaking my own stuff, lol.

I'll fix ReShade's mouse input problems in due time, but I'll do it the right way with pull requests rather than what I was attempting.
