### ISSUE TITLE
Drop FPS

### ISSUE THREAD

**Issue by Katkat95** [Kaldaien/FAR#41]
Hello, since I updated FAR 0.5.6.12, I have a concern about the Framerate without any reason the game freeze whereas with the old version I had no worries. Do you have a solution?
Thank you in advance.

http://imgur.com/a/u9MZS

dxgi.ini = http://rgho.st/8Kky8ZTDv
FAR.ini = http://rgho.st/7Dswyv7cx

OS : Windows 10
CPU : I7-4790K
GPU : MSI GTX 1080TI

**Comment by Kaldaien** [comment]
What exactly am I looking at? They're all the same version, one has high frametime variability the other two look fine. It's he same scene with the same version. Are you sure there's not some outside factor?

Your INI files are not helpful, by the way. If anything I would prefer your logs.

**Comment by Katkat95** [comment]
The worry is that I go from 59,9 FPS to 49 FPS every 30 seconds, so this causes a freeze, even when my character does not move there is still this drop, I tried in several places of the Map I have exactly the same result.

Logs : http://rgho.st/7QfCbgyhW

**Comment by Kaldaien** [comment]
The only thing I notice out of the ordinary in the logs is that you opened the volume management tab. That can take a very long time depending on how many programs you've run since Windows booted. It's a weird design by Microsoft, but they keep a list of every single application that ever played a sound since boot and then I have to go through that list and determine which of those aren't running.

That shows about a 10 second delay in your logs :-\

**Comment by DAOWAce** [comment]
> It's a weird design by Microsoft, but they keep a list of every single application that ever played a sound since boot

Jesus christ, seriously?  So rebooting often is actually a good thing, along with disabling Windows sounds!

I really need to get into programming (and later reverse engineering) so I can see what nightmarish stuff developers have done to programs..  Too bad that journey is 10 years out.

**Comment by Katkat95** [comment]
I tried on the PC of a friend with it also a GTX 1080TI, it has exactly the same worries as me, I tried to defragment my hard drive, reinstall the game, nothing to do the same on another disk Hard, my drivers are up to date I can not find any solution.

**Comment by Katkat95** [comment]
I mute the windows sounds more worries, really strange as a bug. 
Thank you both for your help and courage Kaldaien!
