### ISSUE TITLE
xinput1_3 crashes

### ISSUE THREAD

**Issue by KefRisen** [Kaldaien/FAR#42]
Hello!
My game crash after 10-20 mins.
I see in crash log that problem is related with xinput library.
I've tried several FAR version (0.5.2.17, 0.5.3.2, 0.5.4.2, 0.5.6.9, 0.5.6.12)
Looks like it works fine when i'm using keyboard+mouse, but it's much worse than gamepad.

Here is my logs:
crash.log: https://pastebin.com/i3Dfkwrq
dxgi.log: https://pastebin.com/w38ydbr8
modules.log: https://pastebin.com/9GbQjvwk

Could you please help me with this issue?

**Comment by Kaldaien** [comment]
No, sorry

    05/09/2017 23:27:37.603: [ Module ]  ( 00007FFA02510000h + 00901120 )   -:< 
    SteamInternal_CreateInterface                                    >:-   D:\Games\NieR Automata\steam_api64.dll
     ----------------------  [File Ver]    Steam Client API (buildbot_winslave007@WUS)  01.0.1.08
