### ISSUE TITLE
Game constantly switching between Gamepad and Keyboard interface

### ISSUE THREAD

**Issue by ColonelRVH** [Kaldaien/FAR#45]
Default input interface is keyboard and whenever i press something on the gamepad, the game keep switching between keyboard and gamepad interface, it looks ridiculous. How do I fix this?

There's no problem with this before i use FAR though.

**Comment by ColonelRVH** [comment]
That's weird, i thought the same thing and press Alt again but it didn't fix the problem. 

Though it does now, thanks.

**Comment by Kaldaien** [comment]
This shouldn't be happening with FAR by itself. I have code to prevent that in place, I am aware of quite a few third-party pieces of software that don't properly release keys when their overlays activate though  and cause this.

You may want to confirm that it's not one of those.
