### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by ConnorDY** [Kaldaien/FAR#46]
I'm trying to compile the latest version of FAR myself, but I'm running into an error.

`undeclared identifier "SK_PlugIn_ControlPanelWidget"`

I think this is because you have not updated the source for SpecialK on GitHub.

**Comment by Kaldaien** [comment]
You need the 0.8.x branch of Special K. I'm actually not all that familiar with GitHub so I don't know how to setup dependencies. I'm kind of a dinosaur who used to use Source Forge and CVS, haha.

**Comment by AsukaLangleyfag** [comment]
The way you describe it it's submodules: https://git-scm.com/book/en/v2/Git-Tools-Submodules or on github blog: https://github.com/blog/2104-working-with-submodules

**Comment by ConnorDY** [comment]
I apologize for not even noticing that branch. Thank you!
