### ISSUE TITLE
crash every 30 min with a sound of metalgear (epic)

### ISSUE THREAD

**Issue by hackernich** [Kaldaien/FAR#47]

**Comment by hackernich** [comment]
this is the crash logo ,kaldaien please if you know how answer me thanks ;) 
[! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
05/11/2017 01:35:19.753: -----------------------------------------------------------
05/11/2017 01:35:19.753: [ FaultMod ]  # File.....: ''
05/11/2017 01:35:19.753: [ FaultMod ]  * RIP Addr.: +0000000000000000h
05/11/2017 01:35:19.753: [StackFrame] <-> Rip=000000000000h, Rsp=00023cb46da8h, Rbp=000209abd000h
05/11/2017 01:35:19.753: [StackFrame] >-< Rsi=000140a99790h, Rdi=000136838f20h
05/11/2017 01:35:19.753: [  GP Reg  ]       rax:     0x0000000d418c
05/11/2017 01:35:19.753: [  GP Reg  ]       rbx:     0x000000000000
05/11/2017 01:35:19.753: [  GP Reg  ]       rcx:     0x7b5d78c26c2d0000
05/11/2017 01:35:19.753: [  GP Reg  ]       rdx:     0x000000000000
05/11/2017 01:35:19.753: [  GP Reg  ]        r8:     0x00023cb46808       r9:      0x000209abd000
05/11/2017 01:35:19.753: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
05/11/2017 01:35:19.753: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
05/11/2017 01:35:19.753: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
05/11/2017 01:35:19.753: [ GP Flags ]       EFlags:  0x00010202
05/11/2017 01:35:19.753: -----------------------------------------------------------

**Comment by Kaldaien** [comment]
I can't make heads or tails of that without any context. Please include the other logs too. That crash occurs outside of my code.

**Comment by bk5115545** [comment]
This crashes at a very low address.  It looks like the object, at another low address, 0x0000000d418c, called an inlined function with a prototype that has either 2 or 4 arguments and either 1 or 2 of which were null.  The null argument somehow found it's way onto the stack via offset 0xh and was popped off into rip.  The actual exception is that rip doesn't point to a valid instruction anymore and the program then crashed.

Not actually helpful without debugging symbols but it's some context to help people see how hard this error would be to fix without more information.  Based on the register dump above and the original bug report, I suspect that this is because of some very odd corruption or odd file format causing a bounds overrun/underrun in the engine which leads to data being fed into the audio stream that isn't audio data.  

Try verifying your game and reinstalling the mod.  Make sure to backup saves first.

**Comment by hackernich** [comment]
Kaldaien witch log do you want to see?? 

[dxgi.txt](https://github.com/Kaldaien/FAR/files/995949/dxgi.txt)
[modules.txt](https://github.com/Kaldaien/FAR/files/995950/modules.txt)
[crash.txt](https://github.com/Kaldaien/FAR/files/995951/crash.txt)

**Comment by bk5115545** [comment]
OOoooo thanks for these.

It looks like I mixed up my 0x and h notations a little bit.  The exception is created when a null pointer is called as a function.  The null pointer is created potentially by dereferencing an invalid reference before or after it's been passed to the function at 0x0000000d418c.  What I thought was an object is actually a function that is probably inlined.

This is a cracked game version and the mod literally can't support cracked editions.  The mod relies on fixed memory offsets and addresses which will be different for every slightly different crack.  It's also the reason that the mod has to be updated every single game version and why it had(?) a piracy check until the media went crazy.

When I was reading about the mod, I saw that there was an older, pirate-compatible version.  If you're not running it then please try it but I highly doubt this issue will be addressed either in that version or in the latest as it appears to only affect pirated copies.

**Comment by hackernich** [comment]
you know what version is compatible ?

**Comment by bk5115545** [comment]
I have no idea.  Sorry.

**Comment by Kaldaien** [comment]
@bk5115545: Yes, I have been saying this for who knows how long now and been accused of maliciously disabling certain features in modified versions of the game.

You can't even begin to imagine how frustrating that is. I have code in-place to detect that the addresses don't match up. About 50% of the memory addresses used by the mod are pattern scanned now, 50% remain un-pattern scanned. I was in the process of making that 100% when the pirated version came out and the @#$% hit the fan.

I now have zero intention to ever finish the pattern scanning. If these jerks want to call the protective measures I designed to prevent their game from crashing malware, I'm going to remove those measures altogether and go back to 100% hard-coding the addresses. I don't mind searching for the addresses by hand for the benefit of retail customers if it means ungrateful pirate @#$'s get to crash.

**Comment by DoctorGoat** [comment]
Do you not have code in place to shuffle files maliciously around if it detects a cpy.ini in your dxgi.dll build and you're on a pirated copy? It seems to be triggered by SK_Steam_PiratesAhoy().

**Comment by Kaldaien** [comment]
@DoctorGoat: No, I do not have such code.

SK_Steam_PiratesAhoy (...) triggers nothing, it just validates the used SteamIDs by the cheap hacks pirates use to bypass Denuvo. If detected, SteamAPI features are turned off, or if the user doesn't agree to that, the entire mod is disabled for them.

Protects me very nicely against copyright issues.

**Comment by DoctorGoat** [comment]
I haven't looked at the whole thing until tonight and the SpecialK stuff that I'd need to look at isn't available anymore. Poking around at the dxgi.dll is the only thing I had to go on. I'd genuinely rather have just gone and looked at source.

```
DeleteFileW(L"CPY.ini");`
MoveFileW(L"steam_api64.dll", L"CPY.ini");
MoveFileW(L"steamclient64.dll", L"steam_api64.dll");
MoveFileW(L"CPY.ini", L"steamclient64.dll");
```

This was the triggered code that was concerning me, but I am not used to poking at something that is not a Gameboy Advance and I am entirely okay with admitting I don't know what I'm doing with dll stuff.

Antipiracy is super fascinating and I like to study the subject in general, so... please, don't be ruffled by me being curious, I am just a scholar. If you want to see something glorious, check this: http://www.gamasutra.com/view/feature/131439/keeping_the_pirates_at_bay.php 

There was also this really great thing built into the Wii homebrew installation process for a while where it would ask you if you were going to pirate, and if you said yes, it would lock you out of doing anything until you proved you owned a game by launching it and clearing the preventative code.

**Comment by sterob** [comment]
@Kaldaien or you know you can just ignore them. You know like an internet flame war the more you fan it the more it burns you.

**Comment by Kaldaien** [comment]
If I ignore them, and establish a history of my product being used in copyright infractions, that undermines my ability to generalize Special K. I want to develop this tool into a general-purpose tool that can dump, inject and modify assets in all variety of game. Right now I have texture/shader modding in D3D9/GL/D3D11 and model modding in D3D9. With time, I'll have every asset available for import/export in any game by using the data passed to D3D. At this point, I run the risk of being blanket blacklisted if I don't establish license terms for software use.

**Comment by sterob** [comment]
You don't have to worry about it. Elder's Scroll, Nexus and many game mods didn't run into any problem. May be stick a big EULA every time it runs to give you the legal cover.

**Comment by Kaldaien** [comment]
Elder Scrolls doesn't involve illegally reverse engineering anything. Those are games from the out-right designed to be modified. I don't deal in any games that support modding and often I don't deal with the friendliest of publishers. You've kind of named the polar opposite of who worries me :)

**Comment by sterob** [comment]
Or may be you stop making mod for who come after you so they have to stop selling bad port for $60.

**Comment by Kaldaien** [comment]
That's not being proactive. That's responding to a problem after it happens, which is a giant waste of time. My Special K GitHub repository, for example. Giant waste of time because I didn't adequately protect myself.

**Comment by hackernich** [comment]
kaldaien excuse me i know you are not for pirated games but can you answer me about that crash logo ? 
is caused by your mod ? or it 's another problem ? please answer me if you want thanks ;)

**Comment by hackernich** [comment]
or your mod doesn't work with cracked version ?? and it crash ?

**Comment by Kaldaien** [comment]
I've been politely ignoring you to avoid controversy.

    05/11/2017 01:04:14.042: [ Module ]  ( 00007FFA0A490000h + 06438912 )                                                                              
  
  C:\Users\hackernich\Desktop\NieR.Automata.Day.One.Edition.Cracked\SmartSteamEmu\SmartSteamEmu64.dll
     ----------------------  [File Ver]    Emulates steam  

I can't say conclusively that the crack is the cause of problems, but it tends to be the case since the authors distributing my software won't even listen to me when I tell them what they need to do to stop crashing in illegitimate versions. I will not offer support to pirates, at the most I would be willing to explain to someone who will support them what they've done wrong -- with the expectation that they remove my name.

In reality this doesn't work, they neither respect your wishes nor listen to you when you tell them why what they're doing blows up and then have the audacity to claim I'm being malicious to them. I wash my hands of the whole thing, you'll have to get support elsewhere.

There's a reason I keep tagging and leaving pirate-related support requests open and it's not out of spite or anything like that.

**Comment by RitzyBusiness** [comment]
I am surprised you haven't left the community out of spite, you're a strong individual.  I wish there were more ways to thank you for your effort, making the games I play (Berseria and Nier) much better experiences.
