### ISSUE TITLE
crashing with mgs sounds upon entering the desert area (snaaake)

### ISSUE THREAD

**Issue by Vampshyde** [Kaldaien/FAR#48]
please help sir.

Log Name:      Application
Source:        Application Error
Date:          5/12/2017 4:12:11 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      VampshydeHDD2
Description:
Faulting application name: NieRAutomata.exe, version: 1.0.0.0, time stamp: 0x58ff1395
Faulting module name: ntdll.dll, version: 6.1.7601.17514, time stamp: 0x4ce7c8f9
Exception code: 0xc0000005
Fault offset: 0x0000000000053560
Faulting process id: 0xef8
Faulting application start time: 0x01d2ca922feedf07
Faulting application path: C:\Program Files (x86)\NieR - Automata\NieRAutomata.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 1d61e149-3686-11e7-b5ce-00ac81d767b4
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-11T20:12:11.000000000Z" />
    <EventRecordID>469322</EventRecordID>
    <Channel>Application</Channel>
    <Computer>VampshydeHDD2</Computer>
    <Security />
  </System>
  <EventData>
    <Data>NieRAutomata.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>58ff1395</Data>
    <Data>ntdll.dll</Data>
    <Data>6.1.7601.17514</Data>
    <Data>4ce7c8f9</Data>
    <Data>c0000005</Data>
    <Data>0000000000053560</Data>
    <Data>ef8</Data>
    <Data>01d2ca922feedf07</Data>
    <Data>C:\Program Files (x86)\NieR - Automata\NieRAutomata.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>1d61e149-3686-11e7-b5ce-00ac81d767b4</Data>
  </EventData>
</Event>

**Comment by Kaldaien** [comment]
Sorry, please ask for support from the pirate fork.
