### ISSUE TITLE
crash please ask me to fix?

### ISSUE THREAD

**Issue by harloom** [Kaldaien/FAR#51]
05/14/2017 20:23:54.729: -----------------------------------------------------------
05/14/2017 20:23:54.809: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
05/14/2017 20:23:54.809: -----------------------------------------------------------
05/14/2017 20:23:54.809: [ FaultMod ]  # File.....: ''
05/14/2017 20:23:54.809: [ FaultMod ]  * RIP Addr.: +0000000000000000h
05/14/2017 20:23:54.809: [StackFrame] <-> Rip=000000000000h, Rsp=00007f066da8h, Rbp=000174270400h
05/14/2017 20:23:54.809: [StackFrame] >-< Rsi=000140a99790h, Rdi=00019b251f80h
05/14/2017 20:23:54.809: [  GP Reg  ]       rax:     0x000000000af8
05/14/2017 20:23:54.809: [  GP Reg  ]       rbx:     0x000000000000
05/14/2017 20:23:54.809: [  GP Reg  ]       rcx:     0xa0428a373e2e0000
05/14/2017 20:23:54.810: [  GP Reg  ]       rdx:     0x000000000000
05/14/2017 20:23:54.810: [  GP Reg  ]        r8:     0x00007f066808       r9:      0x000174270400
05/14/2017 20:23:54.810: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
05/14/2017 20:23:54.810: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
05/14/2017 20:23:54.810: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
05/14/2017 20:23:54.810: [ GP Flags ]       EFlags:  0x00010202
05/14/2017 20:23:54.810: -----------------------------------------------------------
05/14/2017 20:23:56.871: -----------------------------------------------------------
05/14/2017 20:23:56.908: -----------------------------------------------------------
05/14/2017 20:23:56.908: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
05/14/2017 20:23:56.908: -----------------------------------------------------------
05/14/2017 20:23:56.908: [ FaultMod ]  # File.....: ''
05/14/2017 20:23:56.908: [ FaultMod ]  * RIP Addr.: +0000000000000000h
05/14/2017 20:23:56.908: [StackFrame] <-> Rip=000000000000h, Rsp=00007f066da8h, Rbp=000174270400h
05/14/2017 20:23:56.908: [StackFrame] >-< Rsi=000140a99790h, Rdi=00019b251f80h
05/14/2017 20:23:56.908: [  GP Reg  ]       rax:     0x000000000af8
05/14/2017 20:23:56.908: [  GP Reg  ]       rbx:     0x000000000000
05/14/2017 20:23:56.908: [  GP Reg  ]       rcx:     0xa0428a373e2e0000
05/14/2017 20:23:56.908: [  GP Reg  ]       rdx:     0x000000000000
05/14/2017 20:23:56.908: [  GP Reg  ]        r8:     0x00007f066808       r9:      0x000174270400
05/14/2017 20:23:56.908: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
05/14/2017 20:23:56.908: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
05/14/2017 20:23:56.908: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
05/14/2017 20:23:56.908: [ GP Flags ]       EFlags:  0x00010202
05/14/2017 20:23:56.908: -----------------------------------------------------------
05/14/2017 20:23:57.456: -----------------------------------------------------------
05/14/2017 20:23:57.471: -----------------------------------------------------------
05/14/2017 20:23:57.471: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
05/14/2017 20:23:57.471: -----------------------------------------------------------
05/14/2017 20:23:57.471: [ FaultMod ]  # File.....: ''
05/14/2017 20:23:57.471: [ FaultMod ]  * RIP Addr.: +0000000000000000h
05/14/2017 20:23:57.471: [StackFrame] <-> Rip=000000000000h, Rsp=00007f066da8h, Rbp=000174270400h
05/14/2017 20:23:57.471: [StackFrame] >-< Rsi=000140a99790h, Rdi=00019b251f80h
05/14/2017 20:23:57.471: [  GP Reg  ]       rax:     0x000000000af8
05/14/2017 20:23:57.471: [  GP Reg  ]       rbx:     0x000000000000
05/14/2017 20:23:57.472: [  GP Reg  ]       rcx:     0xa0428a373e2e0000
05/14/2017 20:23:57.472: [  GP Reg  ]       rdx:     0x000000000000
05/14/2017 20:23:57.472: [  GP Reg  ]        r8:     0x00007f066808       r9:      0x000174270400
05/14/2017 20:23:57.472: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
05/14/2017 20:23:57.472: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
05/14/2017 20:23:57.472: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
05/14/2017 20:23:57.493: [ GP Flags ]       EFlags:  0x00010202
05/14/2017 20:23:57.493: -----------------------------------------------------------
05/14/2017 20:23:57.943: -----------------------------------------------------------

**Comment by Kaldaien** [comment]
What?

You can fix it if you want to, I don't even know what I'm looking at.

Please include the rest of your logs and then I can try to fix it.

**Comment by harloom** [comment]
Sorry, I have a crack game, i buy in steam no crash again
