### ISSUE TITLE
Mgs sound and game don't start.

### ISSUE THREAD

**Issue by Kam64** [Kaldaien/FAR#52]
First of all , thanks for the fix!

It work great for me, but after I close the game and want to reopen it, I just keep getting the MGS sound right after I hit the play button on steam and the game don't open after that. The only way around it is to restart the computer every time I want to play again.

**Comment by Kaldaien** [comment]
Could you please provide logs?

logs/dxgi.log, logs/modules.log and I guess in this case, logs/steam_api.log ?

**Comment by Kam64** [comment]
I fix my problem, just in case this happen to someone else.

The problems appears to happen wherever Fraps is open, so I just close Fraps before opening the game and it open without any issue.

Thanks for the reply and sorry that I forgot to post that I found the solution this morning.

**Comment by Kaldaien** [comment]
Yeah, FRAPS kills a lot of mods. You should look for a replacement when you have the time.
