### ISSUE TITLE
Did you modify the file dxgi.dll?

### ISSUE THREAD

**Issue by HTWER** [Kaldaien/FAR#53]
I want to know whether Far can compatible with Fxaa Tool ???

**Comment by Kaldaien** [comment]
Did I do what?

If you want post-process based shader AA, I would suggest using ReShade. Special K has plug-in support for ReShade and as such I maintain compatibility with ReShade as part of my development process.

**Comment by HTWER** [comment]
What is the Special K?What featrue does it has?

**Comment by Kaldaien** [comment]
dxgi.dll is Special K. I didn't modify it, I wrote it.

**Comment by HTWER** [comment]
you wrote a dxgi.all?It means that every dxgi.dll  wrote by different people is different?

**Comment by Idearum** [comment]
@HTWER If you mean the FXAA Tool/FXAA Post Process Injector that is for Skyrim and hosted on NexusMods then that tool is only compatible with DirectX 9 games, which this game isn't.

And yes, *every* dxgi.dll file written by people are different. The files are merely called the same to make use of the same DLL behaviour of Windows. The only "real" dxgi.dll file is a file created and maintained by Microsoft.

If you want to use FAR with FXAA or SMAA then the best option is to use ReShade. You can find a guide on how to set ReShade up with FAR in [this guide](https://steamcommunity.com/sharedfiles/filedetails/?id=914437196), check the "FAR: ReShade Plug-In" chapter for how to set that up.

**Comment by Kaldaien** [comment]
@HTWER: Yes, I wrote dxgi.dll. The thing is, DLLs are not programs. DLLs are packaged code that implement a minimum set of features. Anyone can write, probably in 15 minutes work, a dxgi.dll replacement that can satisfy everything a program needs dxgi.dll for.

In fact, that DLL will also work as d3d8.dll, d3d9.dll and OpenGL32.dll. It implements all of those interfaces too. A LOT of mod software in games works this way, it will substitute an official Microsoft DLL as a means of getting itself loaded into a game. I don't fulfil everything that ANY of those DLLs are supposed to do directly, and behind the scenes any time the game uses my DLL, I will pass its request on to the official Windows DLL.

So, yeah. If you ever come across a mod that works by dropping a DLL into a game's directory, that's not an official DLL. It's what's referred to as a wrapper or proxy DLL.

**Comment by HTWER** [comment]
Thanks!I am also a programer,but I do not familiar with PlusIng.I will check that page to get more information.
And I am not good at English.Sorry!

**Comment by HTWER** [comment]
I finished the 8th step,but when I open the game,it will quit out immediately.I do not kow why.
![image](https://cloud.githubusercontent.com/assets/18010177/26184743/238bf6a4-3bb9-11e7-80e9-198e6fb2a45d.png)
