### ISSUE TITLE
Cannot exit 9S's hacking mode because of overrided key combination (Start + Back) 

### ISSUE THREAD

**Issue by calculushk** [Kaldaien/FAR#54]
During the progress of the game (Nier), I need to exit hacking mode after finishing some mission. However, the key combination (Start + Back) for exiting hacking mode is overrided by the config menu. No matter how I tried, I cannot exit the hacking mode normally. After ten minutes of trial, I find a "way" to exit the hacking mode, i.e. commit suicide in the game, which may not work in some case or in some games.

So, my suggestion is:
1.Add method inside the config menu to send (Start + Back) combine to the game in order exit the hacking mode to avoid the problem.
2.In the config menu, add an option to disable/enable either Xbox controller / PC keyboard's key override (but not disable both) for opening the config menu.

I think either suggestion will solve the problem for the game uses (Start + Back) for game play. 
I really like your patch for Nier. Hope you can fix this problem soon. Thank you.

**Comment by Kaldaien** [comment]
This is a rough one. I need to make this configurable, but I don't have menu code written to handle gamepad bindings yet.

Finishing that by itself is simple, but I've designed logic that depends on how long a particular button is held down and making that configurable is not very intuitive.

I'll add a button under the `Input/Gamepad` settings to disable gamepad input temporarily until I have time to design a proper solution :)
