### ISSUE TITLE
Nier Automata doesn't launch with FAR; works normally otherwise.

### ISSUE THREAD

**Issue by Liceplant** [Kaldaien/FAR#55]
Hello, looking for troubleshooting help with Nier Automata. Upon clicking Play in my Steam library, I hear the Metal Gear Solid alert noise and the game crashes. The game launches normally when FAR is uninstalled. I've followed Aemony's tweak guide (https://steamcommunity.com/sharedfiles/filedetails/?id=914437196) with both the Automatic and Manual methods, but get the same result either way.

Here are my log files:

crash - https://pastebin.com/cBXTH3E2
dxgi - https://pastebin.com/dsrhniWq
modules - https://pastebin.com/w0gezDBU

Thanks in advance for any help/insight.

**Comment by Kaldaien** [comment]
Probably need to disable RTSS or something like that.

**Comment by Liceplant** [comment]
Yup, FRAPS was the overlay in question. Had it running in the background and didn't even think about it interfering with FAR. Thanks for the quick response and fix!
