### ISSUE TITLE
Can't enter name for save creation

### ISSUE THREAD

**Issue by TheLastRar** [Kaldaien/FAR#56]
Have to uninstall FAR before I can input a name (and be able to create a save profile).

This was mentioned on the steam threads somewhere, but I didn't see an issue on GitHub.

**Comment by Kaldaien** [comment]
I'm not sure I understand the problem.

Are you using the Steam overlay's virtual keyboard? I haven't seen this issue reported on the Steam threads.

**Comment by TheLastRar** [comment]
When you create a new save, the game asks you to input an online name.

In this screen, the text box does not accept any keyboard input (using a physical keyboard), despite menu navigation works using the keyboard.

Uninstalling FAR allows this text box to accept input. 

I've also tried the virtual keyboard, but couldn't get that to work.

Steam thread, for reference http://steamcommunity.com/app/524220/discussions/0/1291816880498085119/

**Comment by Kaldaien** [comment]
I can't reproduce this problem :-\

Can you paste `logs/modules.log` and `logs/dxgi.log`? You can find these quickly by opening the config menu and selecting `File | Browse Logs`

I think you may have some third-party software hooking keyboard input.

**Comment by TheLastRar** [comment]
Requested log files;

https://drive.google.com/open?id=0B5CbO_tryxnvQktQczVmN3VscFU
https://drive.google.com/open?id=0B5CbO_tryxnvVElDcWVubmdVNWc

**Comment by Kaldaien** [comment]
It's possible this is being caused by Nahimic. I've had issues with that software forever (you can see how Nahimic2DevProps.dll basically hijacks the entire dxgi.log once it's been loaded).

This is the first system I've ever seen that uses Nahimic VR, in fact. I don't have any computers that support that to test on.

**Comment by TheLastRar** [comment]
FAR updated earlier today and I can no longer reproduce the issue. (I think I was on 0.5.7.2 before)

I believe NahimicVR came installed with an update to Nahimic 2 (I'm on 2.3.15), but I can't say for certain.

The VR version has its own process, `NahmicVRSvc64.exe`.

Closing this as it appears to be fixed.
