### ISSUE TITLE
Why can't I use the reshader?

### ISSUE THREAD

**Issue by RouderSky** [Kaldaien/FAR#59]
I finished the 8th step,but when I open the game,it will quit out immediately.I can see the Reshade has start-up.
When I remove those files,it works normally!
Far is 5.7.My system is win10.
![image](https://cloud.githubusercontent.com/assets/18010177/26184743/238bf6a4-3bb9-11e7-80e9-198e6fb2a45d.png)
![image](https://cloud.githubusercontent.com/assets/18010177/26203897/9089eac6-3c0f-11e7-8e2a-2ddbc97d10c5.png)

**Comment by Drakonas** [comment]
It would be nice to know the answer to this, as the instructions for the new way to load ReShade is gone now that the SpecialK repo is gone.

**Comment by Idearum** [comment]
The steps for how to load ReShade can be found in this guide, see the "FAR: ReShade Plug-In": http://steamcommunity.com/sharedfiles/filedetails/?id=914437196

As for why @HTWER experiences that issue, sadly I have no idea. The "Import.ReShade64" text shouldn't even be a part of the dxgi.ini file if @HTWER have followed the guide I linked to, as it is created first in step 9 when you actually enable the plugin. I'd say removing FAR completely and reinstalling it might solve the issue.

**Comment by HTWER** [comment]
I found that I can use use ReShader,but when I turn the game to Full-Screen,the game will quit out immediately.Why can I turn to Full-Screen using ReShader?
