### ISSUE TITLE
Alt-tabbing from fullscreen switches to windowed mode and doesn't switch back on focus

### ISSUE THREAD

**Issue by green-s** [Kaldaien/FAR#6]
This may be an issue with the game itself but would it be possible to add an option to fix this?

**Comment by ScTiger1311** [comment]
Press alt+enter

**Comment by green-s** [comment]
Yeah that works as normal. Not a big issue, just most games do it automatically.

**Comment by Kaldaien** [comment]
This is a problem with the game itself.

Making the fullscreen mode switch in D3D11 software is somewhat dangerous with a very high potential to deadlock the software. I have opted never to try ***adding*** that functionality to a game again ;) I will happily disable a game's ability to switch, but cannot safely force it to switch.

I don't think I can fix this, but I'll keep it open. Perhaps just preventing the switch will be enough?

**Comment by Link-Satonaka** [comment]
For those with multiple monitors, fwiw, since the mouse can leave the window in full screen, you can simply pause the game and interact with other windows on other monitors.
