### ISSUE TITLE
v0.5.7.4 memory leak

### ISSUE THREAD

**Issue by Iodid** [Kaldaien/FAR#61]
While using FAR 0.5.7.4 from the 'latest' branch I still get memory leaks and the game crashes every few hours at the exact point when I get the windows memory warning. Sometimes it seems to even disable my monitor on crash and I have to reconnect the dvi cable to get it recognized again.

I can probably rule out any other programm causing the issue because it only happens while nier is running and still happens when only nier and steam are active.

The crash log is empty, though I could post the dgxi.log if it helps.
Wierd thing is that windows taskmanager doesn't show full RAM on crash and RAMmap and the OSD don't show a growing trend either, but I'm no expert in that regard so it's highly possible that I overlooked something.

Edit1:
While running Nier Automata there is a .tmp file loaded into RAM that grows over time like a tumor, although this might also be a page file of windows frantically trying to cope with lacking memory. After one to two hours of gameplay it took up 8,5 gigabyte of RAM (Just for reference: I'm having 32 gigs of RAM). This issue did only occur after installing FAR.

Edit2:
The values of rammap don't quite add up. Rammap shows 17,5 gb mapped files which most of is in standby, but the sum of active and standby ram depicted in file summary is disproportinally smaller than the values shown in the use counts.

OSD values after two hours runtime:
```
Working Set: 3331 MiB (Peak: 4458 MiB),
Committed 10464 MiB (Peak: 10505 MiB),
Adress Space: 11351 MiB (Peak: 11358 MiB)
```

**Comment by Kaldaien** [comment]
If I had to guess, I'd point the finger at the Steam overlay. Most memory leaks that pop up out of the blue with no explanation tend to be caused by it :)

You can turn texture caching off, though it's not going to account for this much memory. If you're using Windows 10, the cache can tune itself to deal with memory pressure and thus shouldn't ever be larger than what can fit in VRAM without spillover.
