### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by jokofourO** [Kaldaien/FAR#62]
Greetings; After installing the patch the process starts launching for a few seconds, and then...Nothing. Not even a crash or anything, game just won't launch.

Removing FAR makes it work again instantly.

Trying with the game file exe says error 0xc000007b.

**Comment by ton21** [comment]
same here..

**Comment by Idearum** [comment]
You might be missing some of the required prerequisites, see the prerequisites chapter of this guide: http://steamcommunity.com/sharedfiles/filedetails/?id=914437196

**Comment by DStrifer** [comment]
Same problem! And NO nothing missing from this "prerequisites", nothing! So what`s the problem? Why this popup update of FAR appears on one second and won`t let start the game or at least update as it asks !? And what to update, I took the latest FAR release.

**Comment by Idearum** [comment]
Reinstall FAR.

**Comment by DStrifer** [comment]
Idearum -  genius! ) just F U.
