### ISSUE TITLE
Help me unlock the framerate

### ISSUE THREAD

**Issue by Mumrick** [Kaldaien/FAR#64]
Hi, so I'm annoyed right now cause I can't seem to unlock the framerate at all. I have a 144hz monitor, I don't know what most of the settings do or what values I should put (can't seem to find any info on it either). I have the framelimiter set to off, ingame vsync is off and the refreshrate is set to 144.

Can someone  just tell me EXACTLY what values I need to change and to WHAT. So I can play it in 144hz and with a framerate to match.

Meanwhile I'll just sit here extending my middle finger to Platinum games and Square Snix for fuckin' us over with this garbage pc version.

**Comment by Idearum** [comment]
See **Enable Higher Frame Rate (>60 FPS)** in this Steam Guide: [Tweak Guide](https://steamcommunity.com/sharedfiles/filedetails/?id=914437196)
