### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by ivanfwc** [Kaldaien/FAR#65]
Hi! I just started using your mod in my automata, i downloaded the latest version v0.61, it seems that i having the sound issue, i think is related to the sound effect, when i disable the sound effect, it did not appear. Please help! Thanks.

**Comment by Idearum** [comment]
Please paste copies of:

            logs/dxgi.log
            logs/modules.log
            logs/crash.log (may be empty, ignore if so)

        to pastebin.com and provide a link to these logs.
