### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by mackingtosh** [Kaldaien/FAR#66]
Please help. 

Crash Log:

06/22/2017 02:19:14.982: -----------------------------------------------------------
06/22/2017 02:19:14.982: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
06/22/2017 02:19:14.983: -----------------------------------------------------------
06/22/2017 02:19:14.983: [ FaultMod ]  # File.....: 'C:\SteamLibrary\steamapps\common\NieRAutomata\NieRAutomata.exe'
06/22/2017 02:19:14.983: [ FaultMod ]  * RIP Addr.: NieRAutomata.exe+0000000000907592h
06/22/2017 02:19:14.983: [StackFrame] <-> Rip=000140907592h, Rsp=00004a11fd80h, Rbp=000000000000h
06/22/2017 02:19:14.983: [StackFrame] >-< Rsi=0001419914c0h, Rdi=00001fec3d18h
06/22/2017 02:19:14.983: [  GP Reg  ]       rax:     0x000028e1b530
06/22/2017 02:19:14.983: [  GP Reg  ]       rbx:     0x0001419914c0
06/22/2017 02:19:14.983: [  GP Reg  ]       rcx:     0x000000000000
06/22/2017 02:19:14.983: [  GP Reg  ]       rdx:     0x000000000000
06/22/2017 02:19:14.983: [  GP Reg  ]        r8:     0x000146f32150       r9:      0xfffffffebef78830
06/22/2017 02:19:14.983: [  GP Reg  ]       r10:     0x000005eac5f8      r11:      0x000000000000
06/22/2017 02:19:14.983: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
06/22/2017 02:19:14.983: [  GP Reg  ]       r14:     0x000000000000      r15:      0x000000000000
06/22/2017 02:19:14.983: [ GP Flags ]       EFlags:  0x00010206
06/22/2017 02:19:14.983: -----------------------------------------------------------
06/22/2017 02:19:15.075: -----------------------------------------------------------
06/22/2017 02:19:15.076: -----------------------------------------------------------
06/22/2017 02:19:15.076: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
06/22/2017 02:19:15.076: -----------------------------------------------------------
06/22/2017 02:19:15.076: [ FaultMod ]  # File.....: 'C:\SteamLibrary\steamapps\common\NieRAutomata\NieRAutomata.exe'
06/22/2017 02:19:15.076: [ FaultMod ]  * RIP Addr.: NieRAutomata.exe+0000000000907592h
06/22/2017 02:19:15.076: [StackFrame] <-> Rip=000140907592h, Rsp=00004a11fd80h, Rbp=000000000000h
06/22/2017 02:19:15.076: [StackFrame] >-< Rsi=0001419914c0h, Rdi=00001fec3d18h
06/22/2017 02:19:15.076: [  GP Reg  ]       rax:     0x000028e1b530
06/22/2017 02:19:15.076: [  GP Reg  ]       rbx:     0x0001419914c0
06/22/2017 02:19:15.076: [  GP Reg  ]       rcx:     0x000000000000
06/22/2017 02:19:15.076: [  GP Reg  ]       rdx:     0x000000000000
06/22/2017 02:19:15.076: [  GP Reg  ]        r8:     0x000146f32150       r9:      0xfffffffebef78830
06/22/2017 02:19:15.076: [  GP Reg  ]       r10:     0x000005eac5f8      r11:      0x000000000000
06/22/2017 02:19:15.076: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
06/22/2017 02:19:15.076: [  GP Reg  ]       r14:     0x000000000000      r15:      0x000000000000
06/22/2017 02:19:15.076: [ GP Flags ]       EFlags:  0x00010206
06/22/2017 02:19:15.076: -----------------------------------------------------------
06/22/2017 02:19:15.084: -----------------------------------------------------------
06/22/2017 02:19:15.085: -----------------------------------------------------------
06/22/2017 02:19:15.085: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
06/22/2017 02:19:15.085: -----------------------------------------------------------
06/22/2017 02:19:15.085: [ FaultMod ]  # File.....: 'C:\SteamLibrary\steamapps\common\NieRAutomata\NieRAutomata.exe'
06/22/2017 02:19:15.085: [ FaultMod ]  * RIP Addr.: NieRAutomata.exe+0000000000907592h
06/22/2017 02:19:15.085: [StackFrame] <-> Rip=000140907592h, Rsp=00004a11fd80h, Rbp=000000000000h
06/22/2017 02:19:15.085: [StackFrame] >-< Rsi=0001419914c0h, Rdi=00001fec3d18h
06/22/2017 02:19:15.085: [  GP Reg  ]       rax:     0x000028e1b530
06/22/2017 02:19:15.085: [  GP Reg  ]       rbx:     0x0001419914c0
06/22/2017 02:19:15.085: [  GP Reg  ]       rcx:     0x000000000000
06/22/2017 02:19:15.085: [  GP Reg  ]       rdx:     0x000000000000
06/22/2017 02:19:15.085: [  GP Reg  ]        r8:     0x000146f32150       r9:      0xfffffffebef78830
06/22/2017 02:19:15.085: [  GP Reg  ]       r10:     0x000005eac5f8      r11:      0x000000000000
06/22/2017 02:19:15.085: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
06/22/2017 02:19:15.085: [  GP Reg  ]       r14:     0x000000000000      r15:      0x000000000000
06/22/2017 02:19:15.085: [ GP Flags ]       EFlags:  0x00010206
06/22/2017 02:19:15.085: -----------------------------------------------------------
06/22/2017 02:19:15.093: -----------------------------------------------------------

**Comment by Idearum** [comment]
Post your dxgi.log and modules.log as well.

**Comment by mackingtosh** [comment]
dxgi - https://pastebin.com/e3FxWwv7
Modules - https://pastebin.com/yDxmNWd7

**Comment by Idearum** [comment]
You're running Bitdefender 2017 with Active Threat Control enabled. Disable that and see if there's any difference. As a gamer myself I actually stopped using BitDefender (despite over half a year remaining on my license) since it screwed up with my games far too often.

**Comment by Idearum** [comment]
It's also possible that something else is hooking into your game, but the dxgi.log you attached is from the auto-updater. Run the game again and then re-upload the dxgi.log file if the BitDefender tweak doesn't pan out.

**Comment by mackingtosh** [comment]
@Idearum yeah it crashed again :( https://pastebin.com/mEuetXn3

**Comment by Idearum** [comment]
Sadly that doesn't says a lot. I'd recommend you to do the following:

* Update your GPU drivers and do a clean install.
* Remove dxgi.ini and FAR.ini to revert FAR to a default state.
* Validate the game cache through Steam.

I'd also recommend you to try some of the stuff listed under **What is the White Screen Issue?** in this [tweak guide](http://steamcommunity.com/sharedfiles/filedetails/?id=914437196 ). Especially the CPU core affinity might be of use.

If nothing of that helps solve the issue then I believe we're out of luck unless Kaldaien sees something in the logs that I missed :(
