### ISSUE TITLE
Crashing during Tower

### ISSUE THREAD

**Issue by Lexicona** [Kaldaien/FAR#69]
I'm coming here with a specific issue.  As someone who speedruns this game, bad PC ports can be the bane of our existence.  Endings A-E is about 6.25 hours for one run, and about 6 hours in, during the 9S and A2 tower ascent, I occassionally crash, and it's common enough to become an issue.  An example of this specific crash is here: https://www.twitch.tv/videos/154825662  I included a bit of it beforehand, and also I apologize for the framerate dropping at sometimes.  I can post logs if i'm able to duplicate it, or if it's stored in the folders.

**Comment by Lexicona** [comment]
I was able to get the logs, and i'm going to post the crash, dxgi, and modules logs.  If you want any more, let me know! 

crash: https://pastebin.com/wHQXpM6m

dxgi: https://pastebin.com/j46C9MyJ

modules: https://pastebin.com/nWC4Cxat

**Comment by Idearum** [comment]
I don't remember that section completely, but the final image with the totally misplaced camera is a typical issue with an unlocked framerate, which have a tendency to break the scripting of the game.

According to modules.log Sophos is also injecting itself into the game with their "Sophos Buffer Overrun Protection". If it's anything like similar security protections in other security applications then it might also be at fault here.

That said, the White Tower seems to be one of the few areas the most affected by the "white screen crash" that the game suffers from as well, which also could be responsible for the crash.

**Comment by Lexicona** [comment]
Thanks @Idearum .  I can probably do a run within the next few days, and confirm what you're suspicious of.  Seeing as though i don't have framerate unlocked, the only issue i can see it being is Sophos, which is something i'll have to figure out how to work around.  I'll keep you updated!

**Comment by Lexicona** [comment]
So an update on whether or not the buffer overrun protection affects.  It does not.  I did a run last night as a test and it crashed in the same place, and the modules log doesnt show the module being there.

**Comment by Idearum** [comment]
Ugh, I was afraid of that. You might want to test some of the stuff out mentioned in the **What is the White Screen Issue?** chapter of this [tweak guide](http://steamcommunity.com/sharedfiles/filedetails/?id=914437196).

If that doesn't help then you probably need to contact Square Enix Support, but I honestly doubt even they would be of help :(

**Comment by Lexicona** [comment]
So i tested the only viable thing in the White Screen crash section, and that didn't fix anything, so i'm back again with another crash.  Same place, same time, same situation

**Comment by Idearum** [comment]
Confirm that it still happens with FAR disabled by renaming dxgi.dll to something else (e.g. dxgi_disabled.dll). If it does, then you'll have to contact Square Enix Support, sadly :(

**Comment by Lexicona** [comment]
I would if I could.  Unfortunately, I cannot reliably play this game for such a long period of time without FAR.  I'm going to use the PC stats part of FAR, as well as load out and in of the game at a point where it might not be unloading memory.  As this is an Exception Access Violation, it's probably a RAM issue, which likely means it's not unloading memory soon enough and crashes.
