### ISSUE TITLE
After first launch the value of GlobalIlluminationWorkgroups is set to 0

### ISSUE THREAD

**Issue by green-s** [Kaldaien/FAR#7]
On first launch it is 128. On subsequent launches it is set to 0 and the ini file is rewritten.

[This call](https://github.com/Kaldaien/FAR/blob/5e9ae32a0260c82cf0b01cd730873e08b1c8157b/nier.cpp#L196) is always returning 0 for whatever reason.

**Comment by PatrickOMFG** [comment]
Having this issue too. Tried setting the file as read only, and in game the setting was still displayed as 0.

**Comment by green-s** [comment]
Fixed in the latest update.
