### ISSUE TITLE
Game is forced to open on wrong monitor, crashes when changed

### ISSUE THREAD

**Issue by Morten242** [Kaldaien/FAR#72]
Just updated the mod and now I can't get it to stay on my primary monitor.

Compat. branch does not have this issue.

**Comment by Idearum** [comment]
I don't think FAR actually changes anything with the monitor setting. That setting is notoriously bad in the game to being with. Anyway, I remember seeing a thread on the discussion boards where a guy who successfully solved it said something about letting it crash which would still store the new monitor in the config file? I honestly don't remember, but I recommend you try searching the Steam discussion boards for the game.

**Comment by Morten242** [comment]
Still, doesn't change the fact that it's fine on the compatibility branch, and master branch has the issue. I don't know what's changed but the fact that it was fine before and not now is a pretty good indicator that something broke.
