### ISSUE TITLE
Red dots all over the image since today's FAR update

### ISSUE THREAD

**Issue by fantauzzi** [Kaldaien/FAR#73]
Today 9-Jul FAR v 0.6.2.4 has installed an update, and ever since the game shows many red and green dots all over the image.

PC is running Nvidia drivers 384.76 with a GTX 1080 under Windows 10 64-bit. Game installed with Steam. I didn't change anything in any .ini file.

**Comment by Sabatasso** [comment]
I have the same issue. Stupid me didn't even backup the 0.6.2.3 version as everything has worked so great, but it's not available for download and it's the version that worked best for me.

**Comment by fantauzzi** [comment]
I have uninstalled it rerunning  the SKIM installer, and then downloaded and manualy installed version [0.6.2.2](https://github.com/Kaldaien/FAR/releases). The red and green dot issue is not reproduced.

**Comment by Sabatasso** [comment]
I reverted back to 0.6.2.2 as well, but the 0.6.2.3 had ~5 frames per second better result with the same settings for me.

**Comment by Idearum** [comment]
0.6.2.5 might include a fix for this, according to other users.

**Comment by Sabatasso** [comment]
0.6.2.5 introduces awful framerate stuttering, though.

Why is 0.6.2.3 removed from download?

**Comment by Idearum** [comment]
Probably because it had an extra file included in it that was assumed to be causing the issue, I think. Not that it matters a lot.

0.6.2.5 mistakenly disabled a certain function, I think, that caused the stuttering. Update to the latest version.

**Comment by Kaldaien** [comment]
Jeeze, I need to look at the issue tracker more often, lol. Nobody ever uses it in the primary dev. project this mod is based on.
