### ISSUE TITLE
[FAR 0.6.2.5]Game Crashes randomly (preferably with Steam BigPicture Overlay enabled)

### ISSUE THREAD

**Issue by r0bc94** [Kaldaien/FAR#76]
After the Update to the latest version (0.6.2.5) of this mod via the integrated updater, the game seems to crash with out a warning or message (the game just closes or "disappear"). It seems like the Steam (BigPicture) Overlay has an impact on this crashes, since this game crashes about 3 times within 10 Minutes with Steam (BigPicture) Overlay enabled and didn't crash without the Steam (BigPicture) Overlay.

Edit: It also happens with 0.6.2.7. Here are the logfiles, which contains content (there was a file called "crash" but it was empty). 
 
[CEGUI](https://pastebin.com/KKLeTvgY)
[dxig](https://pastebin.com/Wv3q40aX)
[game_output](https://pastebin.com/QzvJC31P)
[modules](https://pastebin.com/hDxvKJCF)

**Comment by Kaldaien** [comment]
Should be fixed by now, this was a combination of problems with the Steam overlay and with my code. Perfect storm :-\

**Comment by r0bc94** [comment]
Oh, okay, I will give it a shot. Thanks for your support. I really appreciate it.
