### ISSUE TITLE
Game stutters since last FAR update

### ISSUE THREAD

**Issue by Tastypies** [Kaldaien/FAR#78]
My game stutters since the last FAR update (yesterday). I get FPS drops from 60 to ~30 for about a second when passing certain places (and they are many), meaning the drops are not random.  This definitely didn't happen in the 40+ hours of gameplay before. The desert and places with moving water seem to be especially bad, but it doesn't matter whether I look at the water or not while crossing the spots, the fps drop occurs in any case.

**Comment by Idearum** [comment]
Update to the latest version of FAR.

**Comment by Sabatasso** [comment]
Latest version without stutter (for me) is 0.6.2.2
