### ISSUE TITLE
[FAR 0.6.2.7] Crash on loading saved game

### ISSUE THREAD

**Issue by Gorxor** [Kaldaien/FAR#79]
Windows 7, GeForce GTX970

FAR 0.6.2.2: working fine
FAR 0.6.2.5: white window when starting game
FAR 0.6.2.7: game starts, but crash to desktop when loading save

**Comment by Gorxor** [comment]
FAR 0.6.2.8: same as 0.6.2.7 - game starts, but crash to desktop when loading save

**Comment by Gorxor** [comment]
FAR 0.6.2.10: game starts, loading game possible, but crash to dektop after 5 minutes playing... back to compatibility branch

**Comment by Idearum** [comment]
Post your logs:

            logs/dxgi.log
            logs/modules.log
            logs/crash.log (may be empty, ignore if so)

to pastebin.com and provide a link to these logs.

**Comment by Gorxor** [comment]
Ok, switched back to main branch (0.6.2.10), started game, loaded my test save slot (shortly before going into the sewers to the amusement park), and soon enough... crash to desktop. The same save is working fine with the compatbility branch (played for two hours yesterday).

Link: www.pbernert.com/far_0-6-2-10_logs.zip

**Comment by Idearum** [comment]
I don't see anything special in those logs. I'd recommend you to completely uninstall FAR manually by removing all files in the game folder ***except*** for these ones:

* _CommonRedist
* data
* NieRAutomata.exe
* steam_api64.dll

After that, install the latest version of FAR again and run the game for a while. When it crashes, upload your logs again (especially the crash.log that should preferably capture something at that time).

**Comment by Gorxor** [comment]
uninstalled FAR, removed files/folders, installed current main branch (0.6.2.14)

FAR 0.6.2.14: white window when starting game, no crash log

**Comment by Gorxor** [comment]
FAR 0.7.0.0: on my system it's acting like FAR 0.6.2.10: game starts, loading game possible, but crash to dektop after some time playing (empty crash.log)
