### ISSUE TITLE
help me plz

### ISSUE THREAD

**Issue by polodosky** [Kaldaien/FAR#81]
![image](https://user-images.githubusercontent.com/30096062/28096976-1b0fa71a-6683-11e7-9a08-d40f25badff6.png)
 
The game doesnt start, when I take off the far it instantaneously starts

**Comment by Sabatasso** [comment]
Right click the nier automata folder and uncheck "read only" and apply (to subfolders).

**Comment by polodosky** [comment]
nope, still the same problem

**Comment by Idearum** [comment]
No support is guaranteed for illegitimate copies of the game.

**Comment by marcussacana** [comment]
@polodosky eѕѕeѕ вaвacaѕ aqυi alтo-declarado "coмυnidade" não ajυdaм qυando noтaм qυe você тeм a verѕão pirata do jogo, na realidade, ѕorтe a ѕυa qυe o мod não iniciou, ѕe você вaiхoυ o мod aqui, cυidado... ele irá corroмper o ѕeυ nier ѕe deтecтar o cracĸ... pra eviтar iѕѕo тeм υмa verѕão мodiғicada deѕѕe мod no мeυ giтнυв, de υмa olнada... тenтe eхecυтar o nier coмo administrador oυ renomeie o deғaυlт_dхgi.ini para dхgi.ini e тenтe novaмenтe 
(ιgnore aѕ leтraѕ, apenaѕ para dar тraвalнo pra esses вaвacaѕ qυe ѕó penѕaм eм ѕi мeѕмo)
