### ISSUE TITLE
Can't turn off FPS counter.

### ISSUE THREAD

**Issue by xenabakercakes** [Kaldaien/FAR#83]
When I started Nier with the updated far this time is started with all the On Screen Display options turned on. I was able to turn off everything except the FPS counter. It does not respond to me clicking on it although my controller does vibrate as if it is registering.

**Comment by Kaldaien** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>

The shortcuts are documented in some of my other mods. They were also documented in Special K's repository before that got removed from GitHub 👎

**Comment by Idearum** [comment]
> The shortcuts are documented in some of my other mods. They were also documented in Special K's repository before that got removed from GitHub 👎

Accept my pull request and copy/paste those keybindings to the other projects if necessary. I *believe* I listed all of them?

**Comment by xenabakercakes** [comment]
Hey ya. That seemed to work. Thank You
