### ISSUE TITLE
White screen on launch since an update

### ISSUE THREAD

**Issue by Scratus** [Kaldaien/FAR#84]
Hi guys,

When I tried to launch the game from Steam, a window told me that FAR needed an update, so I just proceeded but now the game doesn't respond anymore. I just have a white screen on launch.

Any ideas?

(Running Windows 7, if this can help)

**Comment by Idearum** [comment]
Uninstall FAR and install FAR v0.7.0 using SKIM64.exe linked in the below release:
https://github.com/Kaldaien/FAR/releases/tag/far_070

**Comment by Scratus** [comment]
Thanks for answering! ;) 
I uninstalled FAR and installed FAR v0.7.0. I didn't use SKIM64.exe though because when I tried to use it, it stopped responding... 
But now the game is running perfectly fine! Thank you :)
