### ISSUE TITLE
[FAR 0.7.0.6] Can't accept SLA

### ISSUE THREAD

**Issue by ds8k** [Kaldaien/FAR#85]
Just installed FAR and I'm unable to click anything in the on-screen menus. If I scroll through it I can see some licensed software titles get selected, at which point if I click then that title is expanded. Despite that, I can't click "I agree" or decline.

**Comment by marcussacana** [comment]
maybe your game is pirate?

**Comment by ds8k** [comment]
@marcussacana More than welcome to look at my Steam profile to verify I'm playing on a legit copy: http://steamcommunity.com/id/darksonic8/

**Comment by marcussacana** [comment]
no problem man, i don't have problem with this just this is a common problem to pirate copy

**Comment by ds8k** [comment]
Well yeah, but then I still can't configure anything in the UI. Seems like an odd choice to make all clicks go to the center of the screen...

**Comment by Idearum** [comment]
>  0.7.0.7 fixes Steam overlay input hook race (again)
> 0.7.0.9 corrects GeForce Experience startup issues

Might've been fixed already, so please update FAR. If you still experience the issue then it most likely is some third-party applications interfering. Attach your log files (dinput8.log, modules.log) here if that's the case.

**Comment by ds8k** [comment]
Issues were fixed with the new versions. Thanks!
