### ISSUE TITLE
Mod detecting "pirated" copy that isn't

### ISSUE THREAD

**Issue by VisceralShadow** [Kaldaien/FAR#88]
Hey, I've played through Automata once already, and was planning on downloading your mod to play through the game again with all the fixes it entails. But when I downloaded the mod, whenever I launched the game played the metal gear sound and refused to open. I looked this up, and apparently it's an anti-cheat measure to make it so people who pirated the game can't use the mod. That would be fine, except for the fact that this is a legitimate copy run through steam family sharing that's getting false flagged. I was wondering if there was a fix for this. [Here's a link to a picture of it in my shared steam library](http://imgur.com/a/iwxOq)

**Comment by marcussacana** [comment]
I think in help but "That would be fine", good lucky man.
