### ISSUE TITLE
MGS sound before crashing.

### ISSUE THREAD

**Issue by ssj4uncleruckus** [Kaldaien/FAR#89]
Hey, just needed a little help figuring why the crash is happening. Can't drop my crash.log so I'm just gonna paste it in here. Lemme know if you need to see anything else, thanks.

08/11/2017 14:35:51.867: -----------------------------------------------------------
08/11/2017 14:35:51.868: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
08/11/2017 14:35:51.868: -----------------------------------------------------------
08/11/2017 14:35:51.868: [ FaultMod ]  # File.....: ''
08/11/2017 14:35:51.868: [ FaultMod ]  * RIP Addr.: +0000000000000000h
08/11/2017 14:35:51.868: [StackFrame] <-> Rip=000000000000h, Rsp=000078796da8h, Rbp=00019d26db00h
08/11/2017 14:35:51.868: [StackFrame] >-< Rsi=000140a99790h, Rdi=00015a0e0ee0h
08/11/2017 14:35:51.868: [  GP Reg  ]       rax:     0x000000000bd0
08/11/2017 14:35:51.868: [  GP Reg  ]       rbx:     0x000000000000
08/11/2017 14:35:51.868: [  GP Reg  ]       rcx:     0x5ff6bb760b4f0000
08/11/2017 14:35:51.868: [  GP Reg  ]       rdx:     0x000000000000
08/11/2017 14:35:51.868: [  GP Reg  ]        r8:     0x000078796858       r9:      0x00019d26db00
08/11/2017 14:35:51.868: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
08/11/2017 14:35:51.868: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
08/11/2017 14:35:51.868: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
08/11/2017 14:35:51.868: [ GP Flags ]       EFlags:  0x00010202
08/11/2017 14:35:51.868: -----------------------------------------------------------
08/11/2017 14:35:51.911: [--(Name)--] [!] {           xinput1_3.dll}                                                         Ordinal95
08/11/2017 14:35:51.911: -----------------------------------------------------------
08/11/2017 14:35:51.913: -----------------------------------------------------------
08/11/2017 14:35:51.913: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
08/11/2017 14:35:51.913: -----------------------------------------------------------
08/11/2017 14:35:51.913: [ FaultMod ]  # File.....: ''
08/11/2017 14:35:51.913: [ FaultMod ]  * RIP Addr.: +0000000000000000h
08/11/2017 14:35:51.913: [StackFrame] <-> Rip=000000000000h, Rsp=000078796da8h, Rbp=00019d26db00h
08/11/2017 14:35:51.913: [StackFrame] >-< Rsi=000140a99790h, Rdi=00015a0e0ee0h
08/11/2017 14:35:51.913: [  GP Reg  ]       rax:     0x000000000bd0
08/11/2017 14:35:51.913: [  GP Reg  ]       rbx:     0x000000000000
08/11/2017 14:35:51.913: [  GP Reg  ]       rcx:     0x5ff6bb760b4f0000
08/11/2017 14:35:51.913: [  GP Reg  ]       rdx:     0x000000000000
08/11/2017 14:35:51.913: [  GP Reg  ]        r8:     0x000078796858       r9:      0x00019d26db00
08/11/2017 14:35:51.913: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
08/11/2017 14:35:51.913: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
08/11/2017 14:35:51.913: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
08/11/2017 14:35:51.913: [ GP Flags ]       EFlags:  0x00010202
08/11/2017 14:35:51.913: -----------------------------------------------------------
08/11/2017 14:35:51.955: [--(Name)--] [!] {           xinput1_3.dll}                                                         Ordinal95
08/11/2017 14:35:51.955: -----------------------------------------------------------
08/11/2017 14:35:51.956: -----------------------------------------------------------
08/11/2017 14:35:51.956: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
08/11/2017 14:35:51.956: -----------------------------------------------------------
08/11/2017 14:35:51.956: [ FaultMod ]  # File.....: ''
08/11/2017 14:35:51.956: [ FaultMod ]  * RIP Addr.: +0000000000000000h
08/11/2017 14:35:51.956: [StackFrame] <-> Rip=000000000000h, Rsp=000078796da8h, Rbp=00019d26db00h
08/11/2017 14:35:51.956: [StackFrame] >-< Rsi=000140a99790h, Rdi=00015a0e0ee0h
08/11/2017 14:35:51.956: [  GP Reg  ]       rax:     0x000000000bd0
08/11/2017 14:35:51.957: [  GP Reg  ]       rbx:     0x000000000000
08/11/2017 14:35:51.957: [  GP Reg  ]       rcx:     0x5ff6bb760b4f0000
08/11/2017 14:35:51.957: [  GP Reg  ]       rdx:     0x000000000000
08/11/2017 14:35:51.957: [  GP Reg  ]        r8:     0x000078796858       r9:      0x00019d26db00
08/11/2017 14:35:51.957: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
08/11/2017 14:35:51.957: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
08/11/2017 14:35:51.957: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
08/11/2017 14:35:51.957: [ GP Flags ]       EFlags:  0x00010202
08/11/2017 14:35:51.957: -----------------------------------------------------------
08/11/2017 14:35:52.001: [--(Name)--] [!] {           xinput1_3.dll}                                                         Ordinal95
08/11/2017 14:35:52.001: -----------------------------------------------------------

**Comment by Idearum** [comment]
Blame your illegitimate copy of the game: https://github.com/Kaldaien/FAR/issues/39
