### ISSUE TITLE
How to change global illumination to low?

### ISSUE THREAD

**Issue by TomKiDo** [Kaldaien/FAR#9]
Hi, 

I tried the mod and use ctrl+shit+backspace to open an UI in the game. But the framereate is still low as before. I heard to change the global illumination to low could help. So could you let me know how can I do this in the game or do I modify some codes in a certain file?

Thank you.

**Comment by drdaxxy** [comment]
Install FAR 0.1.1 or later (preferably using the automated installer), and in the Ctrl+Shift+Backspace you'll find a GI Quality dropdown in the NieR: Automata drawer.

**Comment by FaithLV** [comment]
You can turn it off, there's no noticable quality degradation.

**Comment by drdaxxy** [comment]
@FaithLV In some places, that'll cause problems like this: http://diff.pics/Mj0fTtEfrIIB/1

**Comment by Kaldaien** [comment]
There are three ways of doing this:

 1. FAR.ini, GlobalIlluminationWorkGroups
 2. Command Console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Tab</kbd>) `FAR.GIWorkGroups <number>`
 3. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Backspace</kbd>

The presets are 0,16,32,64,128
