### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by murturl** [Kaldaien/FAR#91]
So I get the update popup. And I press yes.
After a few seconds, the update bar turns fully red, and goes back to blank, nothing happenes.
I keep pressing yes, but the same thing happens over and over again.

**Comment by murturl** [comment]
![1353143](https://user-images.githubusercontent.com/31069233/29364334-079f4b7e-82ce-11e7-9391-44651434e776.png)

**Comment by Idearum** [comment]
Install it manually by downloading [FAR_0_7_0_11.7z](https://github.com/Kaldaien/FAR/releases/download/far_070/FAR_0_7_0_11.7z) and extract its contents in the game folder. Then launch the game. Feel free to click on "No" and set an appropriate delay when it asks you to update. FAR 0.7.0.11 is the latest version, so clicking on Yes will probably just result in that error message of yours occurring again, despite the fact that you have actually already installed it by extracting the contents of the archive to the game folder.
