### ISSUE TITLE
Mouse cursor visibility issue

### ISSUE THREAD

**Issue by MikeMMob** [Kaldaien/FAR#92]
OK, so since installing FAR 0.7.11 I am encountering the issue that the mouse cursor is invisible in game menus (FAR default settings, nothing changed via menu). I had this on some occasions in previous versions (I started with 0.5.5) but restart of the Game always fixed it. Now the mouse is invisible in menus. By using FAR settings I can make it visible again but then it is always visible in-game and the auto hide settings do not work. Thanks in advance for any help.

**Comment by Idearum** [comment]
Are you sure you've removed the old version of FAR entirely? Remove all files and folders in the game folder until only these **remain**: https://steamuserimages-a.akamaihd.net/ugc/808804068655852551/1CC119D2F8F8A2C2AD9519FA15027333A263C31D/

Then reinstall FAR 0.7.0.11 again.

Please be aware that even an uninstall within SKIM doesn't remove *all* files and folders for FAR, especially not older versions (such as 0.5.0.5) that can interfere with the newer version.

**Comment by MikeMMob** [comment]
Hi,

thanks for the reply. I finally solved it by uninstalling with SKIM, deleting FAR's INIs and reinstalling again. In any case, AFAIR, for the cursor to show in manus the option of virtual gamepad cursor needs to be turned off (on by default).

--
Best regards,
Michał

**Comment by Noob11223** [comment]
@MikeMMob Hi, you mentioned "virtual gamepad cursor" option. Where is that option? I don't see it in FAR UI.

I have issues with cursor too, it's not visible in menus with any options I tried, only blinks when moving sometimes.
