### ISSUE TITLE
Crash (incl crash log) (Pirated version, I know I can't expect support:( )

### ISSUE THREAD

**Issue by igomoosrsly** [Kaldaien/FAR#93]
Hey. I'm currently running a pirated version of the game, FitGirl version with Triplesec (codex) crack applied. It includes a "fixed" 0.5.6.9 version of FAR. It's working fine until it randomly crashes anywhere between 5-45 minutes into gameplay.

Hoping there is a solution, though I'm not holding my breath. Will buy the game down the line but currently can't afford it, and could play it then, but the hype was too real and I couldn't wait!

Crash log says the following:

> 08/21/2017 17:58:05.702: -----------------------------------------------------------
08/21/2017 17:58:05.702: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
08/21/2017 17:58:05.702: -----------------------------------------------------------
08/21/2017 17:58:05.702: [ FaultMod ]  # File.....: ''
08/21/2017 17:58:05.702: [ FaultMod ]  * RIP Addr.: +0000000000000000h
08/21/2017 17:58:05.702: [StackFrame] <-> Rip=000000000000h, Rsp=00007b790bd8h, Rbp=000169ec1700h
08/21/2017 17:58:05.702: [StackFrame] >-< Rsi=000140a99790h, Rdi=0001af0553f0h
08/21/2017 17:58:05.702: [  GP Reg  ]       rax:     0x000000000528
08/21/2017 17:58:05.702: [  GP Reg  ]       rbx:     0x000000000000
08/21/2017 17:58:05.702: [  GP Reg  ]       rcx:     0xa704aca2ca760000
08/21/2017 17:58:05.702: [  GP Reg  ]       rdx:     0x000000000000
08/21/2017 17:58:05.702: [  GP Reg  ]        r8:     0x00007b790638       r9:      0x000169ec1700
08/21/2017 17:58:05.702: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
08/21/2017 17:58:05.702: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
08/21/2017 17:58:05.702: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
08/21/2017 17:58:05.702: [ GP Flags ]       EFlags:  0x00010202
08/21/2017 17:58:05.702: -----------------------------------------------------------
08/21/2017 17:58:05.792: -----------------------------------------------------------
08/21/2017 17:58:05.792: -----------------------------------------------------------
08/21/2017 17:58:05.792: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
08/21/2017 17:58:05.792: -----------------------------------------------------------
08/21/2017 17:58:05.792: [ FaultMod ]  # File.....: ''
08/21/2017 17:58:05.792: [ FaultMod ]  * RIP Addr.: +0000000000000000h
08/21/2017 17:58:05.792: [StackFrame] <-> Rip=000000000000h, Rsp=00007b790bd8h, Rbp=000169ec1700h
08/21/2017 17:58:05.792: [StackFrame] >-< Rsi=000140a99790h, Rdi=0001af0553f0h
08/21/2017 17:58:05.792: [  GP Reg  ]       rax:     0x000000000528
08/21/2017 17:58:05.792: [  GP Reg  ]       rbx:     0x000000000000
08/21/2017 17:58:05.793: [  GP Reg  ]       rcx:     0xa704aca2ca760000
08/21/2017 17:58:05.793: [  GP Reg  ]       rdx:     0x000000000000
08/21/2017 17:58:05.793: [  GP Reg  ]        r8:     0x00007b790638       r9:      0x000169ec1700
08/21/2017 17:58:05.793: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
08/21/2017 17:58:05.793: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
08/21/2017 17:58:05.793: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
08/21/2017 17:58:05.793: [ GP Flags ]       EFlags:  0x00010202
08/21/2017 17:58:05.793: -----------------------------------------------------------
08/21/2017 17:58:05.811: -----------------------------------------------------------
08/21/2017 17:58:05.811: -----------------------------------------------------------
08/21/2017 17:58:05.811: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
08/21/2017 17:58:05.811: -----------------------------------------------------------
08/21/2017 17:58:05.811: [ FaultMod ]  # File.....: ''
08/21/2017 17:58:05.811: [ FaultMod ]  * RIP Addr.: +0000000000000000h
08/21/2017 17:58:05.811: [StackFrame] <-> Rip=000000000000h, Rsp=00007b790bd8h, Rbp=000169ec1700h
08/21/2017 17:58:05.811: [StackFrame] >-< Rsi=000140a99790h, Rdi=0001af0553f0h
08/21/2017 17:58:05.811: [  GP Reg  ]       rax:     0x000000000528
08/21/2017 17:58:05.811: [  GP Reg  ]       rbx:     0x000000000000
08/21/2017 17:58:05.811: [  GP Reg  ]       rcx:     0xa704aca2ca760000
08/21/2017 17:58:05.811: [  GP Reg  ]       rdx:     0x000000000000
08/21/2017 17:58:05.811: [  GP Reg  ]        r8:     0x00007b790638       r9:      0x000169ec1700
08/21/2017 17:58:05.811: [  GP Reg  ]       r10:     0x000000000000      r11:      0x000000000246
08/21/2017 17:58:05.811: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
08/21/2017 17:58:05.811: [  GP Reg  ]       r14:     0x000000400000      r15:      0x000000000000
08/21/2017 17:58:05.811: [ GP Flags ]       EFlags:  0x00010202
08/21/2017 17:58:05.811: -----------------------------------------------------------
08/21/2017 17:58:05.830: -----------------------------------------------------------

Any help would be appreciated! :)

**Comment by Idearum** [comment]
Go ask whoever created that "fixed" version of FAR.
