### ISSUE TITLE
FAR menu closes after reaching the title screen

### ISSUE THREAD

**Issue by sharjeel619** [Kaldaien/FAR#94]
When I open the FAR menu. The game blinks before reaching the title screen. And FAR menu closes automatically. I can't bring it up after that. I have tried every possible comb of keys that was advised to use. But it does not work. Pls Help

**Comment by Idearum** [comment]
Please post your modules.log and SpecialK.log from the log subfolder within the game folder to pastebin.com and link them here.

**Comment by skweesh** [comment]
Hey! I have the same problem. There's no specialK.log file, but here's the modules.log https://pastebin.com/P33cuiS4

**Comment by sephie** [comment]
Had the same issue. When I went to the in-game settings and turned off anti-aliasing, the FAR overlay magically appeared.
