### ISSUE TITLE
[ FAR v0.7.0 ] Game wont opened and cursor automatically move to top left corner 

### ISSUE THREAD

**Issue by Koushif** [Kaldaien/FAR#95]
Hi
Im installing this mod to my pirate NierA, and get some problem here

[dinput8](https://pastebin.com/yLDuCrjx)
[modules](https://pastebin.com/Y6iBcxi9)

Laptop Specification
- i5 M460
- AMD HD5730
- 6GB RAM
- Win 7 64x

ty, i hope i get fast respon :+1: i will update if get any error here :dango:

**Comment by Idearum** [comment]
> pirate

There's your issue. FAR doesn't support illegitimate versions of the game. There's forked versions that do, but you'll have to ask their creators for all support related inquiries as we can't help you.

Hope you like the game enough to buy it!

**Comment by Koushif** [comment]
ahh i see, i need buy that game, i hope FAR get more update and another good work for modding graphic game, for potato player like me hehe~

Ty for solved my problem!
