### ISSUE TITLE
Need to reinstall FAR every time I play (dinput8.dll error?)

### ISSUE THREAD

**Issue by Touhou420** [Kaldaien/FAR#96]
When I fresh install FAR I can run NieR fine, but any time I try to launch NieR again it won't launch unless I delete the FAR files (run vanilla NieR) or reinstall FAR so it's back to default settings.

I had a look at the crash log and seems to be a dinput8 error? I attached the 'crash' and 'dinput8' logs, hope you can help because it's super bothersome re-tuning the settings every time I want to play.
BTW I'm using an XBox 360 wireless controller if that matters.

[crash.log](https://github.com/Kaldaien/FAR/files/1327286/crash.log)
[dinput8.log](https://github.com/Kaldaien/FAR/files/1327287/dinput8.log)

**Comment by Idearum** [comment]
Probably a third-party conflict. Post your modules.log as well.

**Comment by Touhou420** [comment]
File attached
[modules.log](https://github.com/Kaldaien/FAR/files/1332436/modules.log)

**Comment by Idearum** [comment]
Hmm, the only thing that stands out is this row:

    09/24/2017 22:08:29.576: [DLL Loader]   ( dxgi.dll                     ) loaded '                                                                                   C:\Windows\system32\DXGIDebug.dll' <LoadLibraryExW> { '          CheckETWTLS' }

It would seem that the game is for some reason loading the debug mode of DirectX 11, if I understand it correctly. Admittedly I am not really familiar with this behavior at all. See if you have a **DirectX Control Panel** on your start menu (or similarly named) that might have an option to disable DirectX debug mode/version.

If you don't, close down all third-party apps to try and find whatever is causing the issue.

If you haven't cleaned out your installation folder you might want to do so by removing all files and folders until only [these remain](https://steamuserimages-a.akamaihd.net/ugc/808804068655852551/1CC119D2F8F8A2C2AD9519FA15027333A263C31D/), and after that reinstall FAR.

**Comment by Touhou420** [comment]
Great work! I got to the DirectX Control Panel by running "dxcpl" in the search bar and added the NieR executable, then chose "Force Off" for the Debug Layer setting. Launched a couple times, one from Steam and then from Steam Big Picture, launched fine both times. Thanks for helping Idearum.
