### ISSUE TITLE
FAR on nosTEAM Nier:Automata

### ISSUE THREAD

**Issue by MelhaouiTarek** [Kaldaien/FAR#97]
Hi
Please i downloaded the game using nosteam.ro and as the majority of people i have fps issues even with a good set up i was just wondering how is is possible to install the FAR since the nosTEAM game got a totally different Nier directory root.
sorry if i kind of only have the basic knowledge about that kind of stuff and sorry for taking from your time =D thanks anyway for reading!

**Comment by Idearum** [comment]
Sorry, but FAR doesn't support illegitimate copies of the game. You'll have to find help somewhere else.
