### ISSUE TITLE
FAR mod force closes game on launch

### ISSUE THREAD

**Issue by lbfs** [Kaldaien/FAR#99]
I'm not sure if they are related, but I just purchased the 3C31C1D119440927 DLC for Nier: Automata, and am using a fresh copy of the game. When I installed FAR, the game now force closes, uninstalling FAR the game works correctly, but obviously losing all the performance enhancements that FAR provides. 

I've attached my error logs, and if more addition information I can post here or you can add me on Steam to troubleshoot 

http://steamcommunity.com/id/lbfs/

Thanks, I really enjoy this game and this mod just makes it better :3

[dinput8.log](https://github.com/Kaldaien/FAR/files/1367327/dinput8.log)
[installer.log](https://github.com/Kaldaien/FAR/files/1367325/installer.log)
[modules.log](https://github.com/Kaldaien/FAR/files/1367328/modules.log)
[steam_api.log](https://github.com/Kaldaien/FAR/files/1367326/steam_api.log)

**Comment by lbfs** [comment]
Installing the mod manually without using skim DOES allow the game to boot, however the fps is even worse than the base game. The settings menu through ctrl+shift+backspace opens but its refreshing incredibly rapidly

**Comment by lbfs** [comment]
Installed older version 6 and it works fine, seems version 7 has some issues.

**Comment by i0ntempest** [comment]
+1 on 0.7.0.14, 0.7.0.11 works fine for me
